/*
 * Detect and strip C2PA / AI-related metadata from PNG, JPEG, WebP, AVIF, HEIC,
 * BMP, GIF and TIFF (classic and BigTIFF).
 *
 * JavaScript port of the stdlib parsers in `service/scripts/image_meta.py`
 * from guillaumemeyer/watermarks-remover (MIT): same chunk/segment/box policy,
 * same marker heuristics, same VP8X flag fix-up. Pixels are never touched —
 * this is byte-level container surgery, not a canvas re-encode.
 *
 * Works as a plain <script> (window.ImageMeta) and as a CommonJS module.
 */
(function (root) {
  "use strict";

  const enc = new TextEncoder();
  const PNG_SIG = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

  const C2PA_MARKERS = ["c2pa", "C2PA", "jumb", "JUMB", "c2ma", "contentcredentials", "contentauth", "cai:",
    "http://ns.adobe.com/xmp/InstanceID/"];
  const AI_META_HINTS = ["c2pa", "C2PA", "contentcredentials", "ContentCredentials", "digitalSourceType",
    "trainedAlgorithmicMedia", "compositeWithTrainedAlgorithmicMedia", "algorithmicMedia", "AIGC", "aigc",
    "AI generated", "Generated by", "Claude", "Anthropic", "OpenAI", "SynthID", "dcterms:provenance"];
  const ALL_HINTS = AI_META_HINTS.concat(C2PA_MARKERS);

  /* JPEG COM is unkeyed free text, so only unambiguous provenance markers are
   * evidence of AI metadata. Bare vendor names and "Generated by" are ordinary
   * comment text too (for example, "Claude Monet" or "Generated by ImageMagick").
   * JPEG_C2PA_MARKERS also replaces C2PA_MARKERS in the whole-file byte scan
   * for JPEG: "jumb" and the XMP InstanceID namespace appear in ordinary files
   * and are only evidence when they sit inside a segment we parsed. */
  const JPEG_C2PA_MARKERS = ["c2pa", "c2ma", "contentcredentials", "contentauth", "cai:"];
  const JPEG_COM_AI_HINTS = JPEG_C2PA_MARKERS.concat(["digitalSourceType", "trainedAlgorithmicMedia",
    "compositeWithTrainedAlgorithmicMedia", "algorithmicMedia", "AIGC", "AI generated", "Generated by AI",
    "SynthID", "dcterms:provenance"]);

  /* Well-known AI generator product/model names. These are matched ONLY against
   * the values of generator-bearing PNG text-chunk keys (Software, Creator,
   * parameters) — see generatorProductHits — and are deliberately kept out of
   * the flat ALL_HINTS blob scan: bare "Gemini", "Sora" or "Firefly" are
   * ordinary words that can appear in captions, and only a generator field
   * makes them evidence of AI provenance. Folding them into ALL_HINTS would
   * produce false positives and diverge from upstream. */
  const AI_GENERATOR_PRODUCTS = ["ChatGPT", "DALL-E", "Midjourney", "Stable Diffusion", "SDXL", "FLUX",
    "DreamStudio", "Leonardo AI", "Leonardo.Ai", "Craiyon", "NovelAI", "Ideogram", "TensorArt", "Recraft",
    "Clipdrop", "DeepAI", "NightCafe", "Bing Image Creator", "Adobe Firefly", "Firefly", "Gemini", "Imagen",
    "Grok", "Sora", "Veo", "Kling", "Runway", "Luma", "Qwen", "GPT-4", "GPT-5"];

  /* PNG text-chunk keys whose value can name the generating model/tool. tEXt /
   * iTXt "Software" and "Creator" are the classic generator fields;
   * "parameters" is what Stable Diffusion WebUI writes with the full
   * generation string. Values of other keys (Comment, Description, Title, ...)
   * are free text and are never scanned for product names. */
  const GENERATOR_TEXT_KEYS = new Set(["software", "creator", "parameters"]);
  const C2PA_STRONG = new Set(["c2pa", "contentcredentials", "jumb", "contentauth"]);
  const C2PA_STRONG_CORE = new Set(["c2pa", "contentcredentials", "jumb"]);

  const latin1 = (u8) => { let s = ""; for (let i = 0; i < u8.length; i++) s += String.fromCharCode(u8[i]); return s; };
  const startsWith = (u8, sig) => sig.every((b, i) => u8[i] === b);
  const be32 = (u8, p) => ((u8[p] << 24) | (u8[p + 1] << 16) | (u8[p + 2] << 8) | u8[p + 3]) >>> 0;
  const be16 = (u8, p) => (u8[p] << 8) | u8[p + 1];
  const le32 = (u8, p) => (u8[p] | (u8[p + 1] << 8) | (u8[p + 2] << 16) | (u8[p + 3] << 24)) >>> 0;
  const le32s = (u8, p) => (u8[p] | (u8[p + 1] << 8) | (u8[p + 2] << 16) | (u8[p + 3] << 24)) | 0;
  const le16 = (u8, p) => u8[p] | (u8[p + 1] << 8);
  const packLe32 = (n) => [n & 0xff, (n >>> 8) & 0xff, (n >>> 16) & 0xff, (n >>> 24) & 0xff];
  const packBe32 = (n) => [(n >>> 24) & 0xff, (n >>> 16) & 0xff, (n >>> 8) & 0xff, n & 0xff];

  /* TIFF needs both byte orders and, for BigTIFF, 64-bit offsets. Values are
   * carried as JS numbers: exact below 2^53, which no real file reaches. */
  const u16at = (u8, p, le) => (le ? le16(u8, p) : be16(u8, p));
  const u32at = (u8, p, le) => (le ? le32(u8, p) : be32(u8, p));
  const u64at = (u8, p, le) => (le
    ? le32(u8, p) + le32(u8, p + 4) * 4294967296
    : be32(u8, p) * 4294967296 + be32(u8, p + 4));
  const packU16 = (n, le) => (le ? [n & 0xff, (n >>> 8) & 0xff] : [(n >>> 8) & 0xff, n & 0xff]);
  const packU32 = (n, le) => (le ? packLe32(n) : packBe32(n));
  const packU64 = (n, le) => {
    const lo = n >>> 0, hi = Math.floor(n / 4294967296) >>> 0;
    return le ? packLe32(lo).concat(packLe32(hi)) : packBe32(hi).concat(packBe32(lo));
  };

  /* ASCII case folding, byte by byte. Upstream _contains_any lowercases the
   * whole blob and every needle; every needle we carry is ASCII, so folding
   * A-Z is the same comparison without decoding the blob at all. */
  const LOWER_BYTE = new Uint8Array(256);
  for (let b = 0; b < 256; b++) LOWER_BYTE[b] = b >= 0x41 && b <= 0x5a ? b + 0x20 : b;

  /* Lowercased needle bytes plus a 256-slot table mapping a folded first byte
   * to the needles starting with it, so the scan skips a byte outright when
   * nothing can start there. */
  function compileNeedles(needles) {
    const pats = needles.map((n) => {
      const bytes = new Uint8Array(n.length);
      for (let i = 0; i < n.length; i++) bytes[i] = LOWER_BYTE[n.charCodeAt(i) & 0xff];
      return bytes;
    });
    const byFirst = new Array(256).fill(null);
    for (let k = 0; k < pats.length; k++) {
      const first = pats[k][0];
      if (byFirst[first] === null) byFirst[first] = [];
      byFirst[first].push(k);
    }
    return { needles, pats, byFirst };
  }

  /* Needle lists are module constants, so each one compiles once per page. */
  const COMPILED_NEEDLES = new WeakMap();

  /**
   * Case-insensitive substring scan of a byte blob, like upstream
   * _contains_any: same needle order in the result, and the same duplicate
   * entries when two spellings of one marker (c2pa and C2PA) match the same
   * bytes. Scans the bytes directly rather than building a latin-1 string of
   * the whole file, which for a multi-megabyte image was the dominant cost of
   * an inspect or clean pass.
   */
  function containsAny(u8, needles) {
    let compiled = COMPILED_NEEDLES.get(needles);
    if (!compiled) { compiled = compileNeedles(needles); COMPILED_NEEDLES.set(needles, compiled); }
    const { pats, byFirst } = compiled;
    const hit = new Uint8Array(pats.length);
    let remaining = pats.length;
    const n = u8.length;
    for (let i = 0; i < n && remaining; i++) {
      const candidates = byFirst[LOWER_BYTE[u8[i]]];
      if (candidates === null) continue;
      for (let c = 0; c < candidates.length; c++) {
        const k = candidates[c];
        if (hit[k]) continue;
        const pat = pats[k], len = pat.length;
        if (i + len > n) continue;
        let j = 1;
        while (j < len && LOWER_BYTE[u8[i + j]] === pat[j]) j++;
        if (j === len) { hit[k] = 1; remaining--; }
      }
    }
    const found = [];
    for (let k = 0; k < needles.length; k++) if (hit[k]) found.push(needles[k]);
    return found;
  }

  const AVIF_BRANDS = ["avif", "avis", "avio"];
  const HEIC_BRANDS = ["heic", "heix", "hevc", "heim", "heis", "mif1", "msf1", "heif"];

  function detectFormat(u8) {
    if (u8.length >= 8 && startsWith(u8, PNG_SIG)) return "png";
    if (u8.length >= 2 && u8[0] === 0xff && u8[1] === 0xd8) return "jpeg";
    if (u8.length >= 12 && latin1(u8.subarray(0, 4)) === "RIFF" && latin1(u8.subarray(8, 12)) === "WEBP") return "webp";
    if (u8.length >= 12 && latin1(u8.subarray(4, 8)) === "ftyp") {
      const boxSize = be32(u8, 0);
      // Brand match is case-sensitive here, unlike the marker heuristics below.
      const end = boxSize >= 8 ? Math.min(boxSize, u8.length, 64) : Math.min(u8.length, 64);
      const header = latin1(u8.subarray(8, Math.max(8, end)));
      if (AVIF_BRANDS.some((b) => header.includes(b))) return "avif";
      if (HEIC_BRANDS.some((b) => header.includes(b))) return "heic";
    }
    if (u8.length >= 2 && u8[0] === 0x42 && u8[1] === 0x4d) return "bmp";
    if (u8.length >= 6 && ["GIF87a", "GIF89a"].includes(latin1(u8.subarray(0, 6)))) return "gif";
    if (tiffLayout(u8) !== null) return "tiff";
    return "unknown";
  }

  function concat(parts) {
    let n = 0; for (const p of parts) n += p.length;
    const out = new Uint8Array(n); let o = 0;
    for (const p of parts) { out.set(p, o); o += p.length; }
    return out;
  }

  /* Minimal synchronous DEFLATE (RFC 1951), with the optional zlib wrapper
   * (RFC 1950) skipped when present. Upstream reads PNG zTXt/iTXt payloads
   * with zlib.decompress; inspect()/clean() are synchronous here and the only
   * inflate a browser ships (DecompressionStream) is async, so we carry our
   * own rather than turn the whole API async.
   * Returns null on anything malformed — callers treat that exactly the way
   * upstream treats zlib.error: silently yield no entries, never raise. */
  const INFLATE_MAX_OUTPUT = 16 * 1024 * 1024;  // guards against zip bombs
  const LEN_BASE = [3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 15, 17, 19, 23, 27, 31, 35, 43, 51, 59, 67, 83, 99, 115,
    131, 163, 195, 227, 258];
  const LEN_EXTRA = [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 0];
  const DIST_BASE = [1, 2, 3, 4, 5, 7, 9, 13, 17, 25, 33, 49, 65, 97, 129, 193, 257, 385, 513, 769, 1025,
    1537, 2049, 3073, 4097, 6145, 8193, 12289, 16385, 24577];
  const DIST_EXTRA = [0, 0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11, 12,
    12, 13, 13];
  const CLEN_ORDER = [16, 17, 18, 0, 8, 7, 9, 6, 10, 5, 11, 4, 12, 3, 13, 2, 14, 1, 15];

  /* Canonical Huffman decoding table: how many codes exist per bit length, and
   * the symbols sorted by (length, symbol) — the classic counts/offsets form. */
  function huffTable(lengths) {
    let maxLen = 0;
    for (const l of lengths) if (l > maxLen) maxLen = l;
    if (maxLen === 0) return null;
    const counts = new Array(maxLen + 1).fill(0);
    for (const l of lengths) if (l) counts[l]++;
    const offsets = new Array(maxLen + 2).fill(0);
    for (let i = 1; i <= maxLen; i++) offsets[i + 1] = offsets[i] + counts[i];
    const sorted = new Array(offsets[maxLen + 1]);
    for (let sym = 0; sym < lengths.length; sym++) {
      if (lengths[sym]) sorted[offsets[lengths[sym]]++] = sym;
    }
    return { counts, sorted, maxLen };
  }

  let FIXED_LIT = null, FIXED_DIST = null;
  function fixedTables() {
    if (!FIXED_LIT) {
      const lit = new Array(288);
      for (let i = 0; i < 288; i++) lit[i] = i < 144 ? 8 : i < 256 ? 9 : i < 280 ? 7 : 8;
      FIXED_LIT = huffTable(lit);
      FIXED_DIST = huffTable(new Array(30).fill(5));
    }
    return [FIXED_LIT, FIXED_DIST];
  }

  function inflate(u8) {
    try {
      let pos = 0;
      // zlib wrapper: CM must be 8 and the 2-byte header is a multiple of 31.
      if (u8.length >= 2 && (u8[0] & 0x0f) === 8 && (((u8[0] << 8) | u8[1]) % 31) === 0) {
        if (u8[1] & 0x20) return null;  // preset dictionary — not supported
        pos = 2;
      }
      let bitBuf = 0, bitCnt = 0;
      let out = new Uint8Array(1024), outLen = 0;

      const bits = (n) => {
        if (n === 0) return 0;
        while (bitCnt < n) {
          if (pos >= u8.length) throw new Error("eof");
          bitBuf |= u8[pos++] << bitCnt;
          bitCnt += 8;
        }
        const v = bitBuf & ((1 << n) - 1);
        bitBuf >>>= n; bitCnt -= n;
        return v;
      };
      const decode = (t) => {
        if (!t) throw new Error("no table");
        let code = 0, first = 0, index = 0;
        for (let len = 1; len <= t.maxLen; len++) {
          code |= bits(1);
          const count = t.counts[len];
          if (code - first < count) return t.sorted[index + (code - first)];
          index += count;
          first = (first + count) << 1;
          code <<= 1;
        }
        throw new Error("bad code");
      };
      const grow = (extra) => {
        if (outLen + extra <= out.length) return;
        if (outLen + extra > INFLATE_MAX_OUTPUT) throw new Error("too large");
        let cap = out.length;
        while (cap < outLen + extra) cap *= 2;
        const next = new Uint8Array(Math.min(cap, INFLATE_MAX_OUTPUT));
        next.set(out.subarray(0, outLen));
        out = next;
      };

      for (;;) {
        const final = bits(1);
        const type = bits(2);
        if (type === 0) {
          // Stored: the partial byte is dropped, then LEN/NLEN come raw.
          bitBuf = 0; bitCnt = 0;
          if (pos + 4 > u8.length) throw new Error("eof");
          const len = u8[pos] | (u8[pos + 1] << 8);
          const nlen = u8[pos + 2] | (u8[pos + 3] << 8);
          pos += 4;
          if ((len ^ 0xffff) !== nlen) throw new Error("bad stored block");
          if (pos + len > u8.length) throw new Error("eof");
          grow(len);
          out.set(u8.subarray(pos, pos + len), outLen);
          outLen += len; pos += len;
        } else if (type === 1 || type === 2) {
          let litTable, distTable;
          if (type === 1) {
            [litTable, distTable] = fixedTables();
          } else {
            const hlit = bits(5) + 257, hdist = bits(5) + 1, hclen = bits(4) + 4;
            const clens = new Array(19).fill(0);
            for (let i = 0; i < hclen; i++) clens[CLEN_ORDER[i]] = bits(3);
            const clTable = huffTable(clens);
            const lengths = new Array(hlit + hdist).fill(0);
            for (let i = 0; i < lengths.length;) {
              const sym = decode(clTable);
              if (sym < 16) { lengths[i++] = sym; continue; }
              let repeat, value = 0;
              if (sym === 16) {
                if (i === 0) throw new Error("bad repeat");
                value = lengths[i - 1]; repeat = 3 + bits(2);
              } else if (sym === 17) { repeat = 3 + bits(3); } else { repeat = 11 + bits(7); }
              if (i + repeat > lengths.length) throw new Error("bad repeat");
              for (let k = 0; k < repeat; k++) lengths[i++] = value;
            }
            litTable = huffTable(lengths.slice(0, hlit));
            distTable = huffTable(lengths.slice(hlit));
          }
          for (;;) {
            const sym = decode(litTable);
            if (sym === 256) break;
            if (sym < 256) { grow(1); out[outLen++] = sym; continue; }
            const li = sym - 257;
            if (li >= LEN_BASE.length) throw new Error("bad length code");
            const length = LEN_BASE[li] + bits(LEN_EXTRA[li]);
            const di = decode(distTable);
            if (di >= DIST_BASE.length) throw new Error("bad distance code");
            const dist = DIST_BASE[di] + bits(DIST_EXTRA[di]);
            if (dist > outLen) throw new Error("distance too far back");
            grow(length);
            for (let k = 0; k < length; k++) { out[outLen] = out[outLen - dist]; outLen++; }
          }
        } else {
          throw new Error("reserved block type");
        }
        if (final) break;
      }
      return out.subarray(0, outLen);
    } catch (_) {
      return null;
    }
  }

  // ---------------------------------------------------------------- PNG
  function* pngChunks(u8) {
    let pos = 8;
    while (pos + 8 <= u8.length) {
      const length = be32(u8, pos);
      const type = latin1(u8.subarray(pos + 4, pos + 8));
      const start = pos + 8, end = start + length;
      if (end + 4 > u8.length) { yield { type, truncated: true, offset: pos }; return; }
      yield { type, payload: u8.subarray(start, end), raw: u8.subarray(pos, end + 4) };
      if (type === "IEND") return;
      pos = end + 4;
    }
  }

  const utf8Dec = typeof TextDecoder !== "undefined" ? new TextDecoder("utf-8") : null;
  const utf8 = (u8) => (utf8Dec ? utf8Dec.decode(u8) : latin1(u8));

  /* Parse a PNG text-chunk payload into [key, value] pairs. Handles tEXt
   * (latin-1), zTXt (zlib-compressed text) and iTXt (UTF-8, optionally
   * compressed). Malformed or undecodable chunks yield whatever pairs are
   * recoverable; nothing is thrown. */
  function pngTextEntries(payload, ctype) {
    const nul = payload.indexOf(0);
    if (nul < 0) return [];
    const key = latin1(payload.subarray(0, nul));
    const rest = payload.subarray(nul + 1);
    if (ctype === "tEXt") return [[key, latin1(rest)]];
    if (ctype === "zTXt") {
      if (rest.length < 2) return [];
      const text = inflate(rest.subarray(1));  // skip the compression-method byte
      if (text === null) return [];
      return [[key, latin1(text)]];
    }
    if (ctype === "iTXt") {
      if (rest.length < 4) return [];
      const compFlag = rest[0];
      let r = rest.subarray(2);                // skip compression flag + method
      const langEnd = r.indexOf(0);
      if (langEnd < 0) return [];
      r = r.subarray(langEnd + 1);
      const tkeyEnd = r.indexOf(0);
      if (tkeyEnd < 0) return [];
      let text = r.subarray(tkeyEnd + 1);
      if (compFlag === 1) {
        text = inflate(text);
        if (text === null) return [];
      }
      return [[key, utf8(text)]];
    }
    return [];
  }

  /* Product-name hits scoped to generator-bearing text-chunk keys. Returns
   * labels like "Software=ChatGPT". Case-insensitive substring match on the
   * value, mirroring containsAny but only for GENERATOR_TEXT_KEYS. */
  function generatorProductHits(entries) {
    const hits = [];
    for (const [key, value] of entries) {
      const k = key.trim();
      if (!GENERATOR_TEXT_KEYS.has(k.toLowerCase())) continue;
      const low = value.toLowerCase();
      for (const product of AI_GENERATOR_PRODUCTS) {
        if (low.includes(product.toLowerCase())) hits.push(`${k}=${product}`);
      }
    }
    return hits;
  }

  /* Flat-marker and product-name hits from a PNG text chunk. Flat markers are
   * matched against the raw payload *and* the decoded text, so a marker that
   * only exists inside a compressed zTXt/iTXt payload is still caught. */
  function pngTextHits(payload, ctype) {
    const entries = pngTextEntries(payload, ctype);
    const decoded = enc.encode(entries.map(([, value]) => value).join("\n"));
    const blob = concat([payload, new Uint8Array([0x0a]), decoded]);
    return [containsAny(blob, ALL_HINTS), generatorProductHits(entries)];
  }

  /* True when a PNG text chunk carries AI/C2PA markers. Flat markers match the
   * raw payload and decoded text; generator product names only match the
   * values of generator-bearing keys. */
  function textChunkIsAi(payload, ctype) {
    const [hits, productHits] = pngTextHits(payload, ctype);
    return hits.length > 0 || productHits.length > 0;
  }

  function inspectPng(u8) {
    const findings = []; let hasC2pa = false, hasAi = false;
    if (detectFormat(u8) !== "png") return { hasC2pa: false, hasAi: false, findings: ["not a PNG"] };
    for (const c of pngChunks(u8)) {
      // Upstream renders the chunk type with Python's repr() here, so the
      // literal b'...' wrapper is part of the finding string the parity
      // suite compares. Cosmetic upstream, load-bearing for us.
      if (c.truncated) { findings.push(`truncated chunk b'${c.type}'`); break; }
      if (c.type === "caBX" || c.type === "juMB" || c.type === "jumb" || c.type.startsWith("c2")) {
        hasC2pa = true; findings.push(`PNG chunk ${c.type} (possible C2PA container)`);
      }
      if (["tEXt", "zTXt", "iTXt", "eXIf"].includes(c.type)) {
        // eXIf is deliberately excluded: it holds no PNG text keys to scope by,
        // and no text to decode, so it keeps the plain payload scan.
        const [hits, productHits] = c.type === "eXIf"
          ? [containsAny(c.payload, ALL_HINTS), []]
          : pngTextHits(c.payload, c.type);
        if (hits.length || productHits.length) {
          hasAi = true;
          if (hits.some((h) => C2PA_STRONG_CORE.has(h.toLowerCase()))) hasC2pa = true;
          const parts = hits.length ? [hits.slice(0, 8).join(", ")] : [];
          if (productHits.length) parts.push(`AI generator (${productHits.slice(0, 8).join(", ")})`);
          findings.push(`PNG ${c.type}: ${parts.join("; ")}`);
        }
      }
    }
    const whole = containsAny(u8, C2PA_MARKERS);
    if (whole.length && !hasC2pa) { hasC2pa = true; findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(", ")}`); }
    return { hasC2pa, hasAi: hasAi || hasC2pa, findings };
  }

  const PNG_STRUCTURAL = new Set(["IHDR", "IDAT", "IEND", "PLTE", "tRNS", "gAMA", "pHYs", "sRGB", "cHRM", "iCCP"]);

  function stripPng(u8, { stripAllText = true } = {}) {
    if (detectFormat(u8) !== "png") throw new Error("not PNG");
    const actions = []; const out = [new Uint8Array(PNG_SIG)];
    for (const c of pngChunks(u8)) {
      if (c.truncated) {
        // A truncated chunk (an interrupted download): copy the remainder
        // verbatim instead of dropping it. Dropping turned a recoverable image
        // into an unopenable husk while reporting "already clean" (upstream
        // #170). Recorded as an action so the run is never mistaken for an
        // ordinary no-op clean.
        out.push(u8.subarray(c.offset));
        actions.push(`kept ${u8.length - c.offset} bytes of truncated chunk ${c.type} tail (file truncated)`);
        break;
      }
      let drop = false;
      if (c.type === "eXIf" || c.type === "caBX" || c.type.startsWith("c2")) {
        drop = true; actions.push(`drop chunk ${c.type}`);
      } else if (["tEXt", "zTXt", "iTXt"].includes(c.type)) {
        if (stripAllText || textChunkIsAi(c.payload, c.type)) { drop = true; actions.push(`drop chunk ${c.type}`); }
      } else if (!PNG_STRUCTURAL.has(c.type) && containsAny(concat([enc.encode(c.type), c.payload]), C2PA_MARKERS).length) {
        drop = true; actions.push(`drop chunk ${c.type} (C2PA marker in payload)`);
      }
      if (!drop) out.push(c.raw);
    }
    if (!actions.length) actions.push("no PNG metadata chunks removed (already clean or none matched)");
    return { data: concat(out), actions };
  }

  // ---------------------------------------------------------------- JPEG
  function inspectJpeg(u8) {
    const findings = []; let hasC2pa = false, hasAi = false;
    if (detectFormat(u8) !== "jpeg") return { hasC2pa: false, hasAi: false, findings: ["not a JPEG"] };
    let i = 2; const n = u8.length;
    while (i + 4 <= n) {
      if (u8[i] !== 0xff) { i++; continue; }
      while (i < n && u8[i] === 0xff) i++;
      if (i >= n) break;
      const marker = u8[i]; i++;
      if (marker === 0xd8 || marker === 0xd9) continue;
      if (marker === 0xda) break;
      if (marker >= 0xd0 && marker <= 0xd7) continue;
      if (i + 2 > n) break;
      const seglen = be16(u8, i);
      if (seglen < 2 || i + seglen > n) { findings.push(`bad segment length at marker 0x${marker.toString(16).toUpperCase()}`); break; }
      const payload = u8.subarray(i + 2, i + seglen); i += seglen;
      if (marker === 0xfe) { // COM
        const hits = containsAny(payload, JPEG_COM_AI_HINTS);
        if (hits.length) {
          hasAi = true;
          if (hits.some((h) => C2PA_STRONG.has(h.toLowerCase()))) hasC2pa = true;
          findings.push(`JPEG COM: ${hits.slice(0, 8).join(", ")}`);
        }
      }
      if (marker === 0xeb) { hasC2pa = true; findings.push("JPEG APP11 segment (JUMBF/C2PA common)"); }
      if ([0xe1, 0xe2, 0xed, 0xee, 0xeb].includes(marker)) {
        const hits = containsAny(payload, ALL_HINTS);
        if (hits.length) {
          hasAi = true;
          if (hits.some((h) => C2PA_STRONG.has(h.toLowerCase()))) hasC2pa = true;
          findings.push(`JPEG APP${marker - 0xe0}: ${hits.slice(0, 8).join(", ")}`);
        }
      }
    }
    const whole = containsAny(u8, JPEG_C2PA_MARKERS);
    if (whole.length && !hasC2pa) { hasC2pa = true; findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(", ")}`); }
    return { hasC2pa, hasAi: hasAi || hasC2pa, findings };
  }

  function stripJpeg(u8, { stripAllApp = true } = {}) {
    if (detectFormat(u8) !== "jpeg") throw new Error("not JPEG");
    const actions = []; const out = [new Uint8Array([0xff, 0xd8])];
    let i = 2; const n = u8.length;
    while (i < n) {
      if (u8[i] !== 0xff) { out.push(u8.subarray(i)); actions.push("copied remainder after non-marker byte"); break; }
      while (i < n && u8[i] === 0xff) i++;
      if (i >= n) break;
      const marker = u8[i]; i++;
      if (marker === 0xd9) { out.push(new Uint8Array([0xff, 0xd9])); break; }
      if (marker === 0xd8) continue;
      if (marker >= 0xd0 && marker <= 0xd7) { out.push(new Uint8Array([0xff, marker])); continue; }
      if (marker === 0xda) {
        if (i + 2 > n) break;
        out.push(new Uint8Array([0xff, 0xda])); out.push(u8.subarray(i));
        actions.push("preserved entropy-coded scan (SOS→EOF)");
        break;
      }
      if (i + 2 > n) break;
      const seglen = be16(u8, i);
      if (seglen < 2 || i + seglen > n) { out.push(u8.subarray(i - 2)); actions.push("truncated segment; copied remainder"); break; }
      const payload = u8.subarray(i + 2, i + seglen);
      let keep = false, drop = false;
      if (marker >= 0xe0 && marker <= 0xef) {
        if (marker === 0xeb) { drop = true; actions.push("drop APP11 (C2PA/JUMBF)"); }
        else if (stripAllApp && marker !== 0xe0) { drop = true; actions.push(`drop APP${marker - 0xe0}`); }
        else if (containsAny(payload, ALL_HINTS).length) { drop = true; actions.push(`drop APP${marker - 0xe0} (AI/C2PA markers)`); }
        else keep = true;
      } else if (marker === 0xfe) { // COM
        if (stripAllApp || containsAny(payload, JPEG_COM_AI_HINTS).length) { drop = true; actions.push("drop COM comment"); }
        else keep = true;
      } else keep = true;
      if (keep && !drop) { out.push(new Uint8Array([0xff, marker])); out.push(u8.subarray(i, i + seglen)); }
      i += seglen;
    }
    if (!actions.length) actions.push("no JPEG APP segments removed");
    return { data: concat(out), actions };
  }

  // ---------------------------------------------------------------- WebP
  function webpChunks(u8) {
    if (detectFormat(u8) !== "webp") return { chunks: [], notes: ["not a WebP"] };
    const notes = [];
    const declared = le32(u8, 4);
    if (declared + 8 !== u8.length) notes.push(`RIFF size mismatch: header=${declared + 8} actual=${u8.length}`);
    const chunks = []; let pos = 12;
    while (pos + 8 <= u8.length) {
      const fourcc = latin1(u8.subarray(pos, pos + 4));
      const length = le32(u8, pos + 4);
      const ps = pos + 8, pe = ps + length, padded = pe + (length & 1);
      if (padded > u8.length) { notes.push(`truncated WebP chunk ${fourcc}`); break; }
      chunks.push({ fourcc, payload: u8.subarray(ps, pe), padding: u8.subarray(pe, padded) });
      pos = padded;
    }
    if (pos !== u8.length && !notes.some((x) => x.includes("truncated"))) notes.push(`trailing WebP bytes: ${u8.length - pos}`);
    return { chunks, notes };
  }

  function inspectWebp(u8) {
    const { chunks, notes } = webpChunks(u8);
    const findings = notes.slice();
    if (!chunks.length && notes[0] === "not a WebP") return { hasC2pa: false, hasAi: false, findings };
    let hasC2pa = false, hasAi = false;
    for (const c of chunks) {
      if (c.fourcc.toUpperCase() === "C2PA") { hasC2pa = true; hasAi = true; findings.push("WebP C2PA chunk"); continue; }
      if (c.fourcc === "XMP " || c.fourcc === "EXIF") {
        const hits = containsAny(c.payload, ALL_HINTS);
        if (hits.length) {
          hasAi = true;
          if (hits.some((h) => C2PA_STRONG.has(h.toLowerCase()))) hasC2pa = true;
          findings.push(`WebP ${c.fourcc}: ${hits.slice(0, 8).join(", ")}`);
        }
      }
    }
    return { hasC2pa, hasAi: hasAi || hasC2pa, findings };
  }

  const WEBP_META_FLAGS = { ICCP: 0x20, EXIF: 0x08, "XMP ": 0x04 };

  function stripWebp(u8, { stripAllMetadata = true } = {}) {
    const { chunks, notes } = webpChunks(u8);
    if (!chunks.length && notes[0] === "not a WebP") throw new Error("not WebP");
    if (notes.length) throw new Error("malformed WebP: " + notes.join("; "));
    const actions = []; const kept = []; let removedFlags = 0;
    for (const c of chunks) {
      let drop = c.fourcc.toUpperCase() === "C2PA";
      if (c.fourcc in WEBP_META_FLAGS) drop = stripAllMetadata || containsAny(c.payload, ALL_HINTS).length > 0;
      if (drop) { actions.push(`drop WebP chunk ${c.fourcc}`); removedFlags |= WEBP_META_FLAGS[c.fourcc] || 0; }
      else kept.push(c);
    }
    const body = [enc.encode("WEBP")];
    for (const c of kept) {
      let payload = c.payload;
      if (c.fourcc === "VP8X" && payload.length >= 1 && removedFlags) {
        payload = new Uint8Array(payload); payload[0] &= ~removedFlags;
      }
      body.push(enc.encode(c.fourcc), new Uint8Array(packLe32(payload.length)), payload);
      if (payload.length & 1) body.push(c.padding.length ? c.padding : new Uint8Array([0]));
    }
    const bodyBytes = concat(body);
    if (!actions.length) actions.push("no WebP metadata chunks removed (already clean or none matched)");
    return { data: concat([enc.encode("RIFF"), new Uint8Array(packLe32(bodyBytes.length)), bodyBytes]), actions };
  }

  // ------------------------------------------------------- AVIF / HEIC (ISOBMFF)
  const XMP_UUID = [0xbe, 0x7a, 0xcf, 0xcb, 0x97, 0xa9, 0x42, 0xe8, 0x9c, 0x71, 0x99, 0x94, 0x91, 0xe3, 0xaf, 0xac];

  /* Parse top-level or container boxes. Returns { boxes, scannedEnd }, where
   * scannedEnd is the offset the walk stopped at: the start of the first box
   * that could not be parsed (one whose declared size overruns the data, or a
   * run of fewer than 8 trailing bytes), or `end` when everything parsed. */
  function parseIsobmffBoxes(u8, start = 0, end = null) {
    if (end === null) end = u8.length;
    const boxes = [];
    let pos = start;
    while (pos + 8 <= end) {
      let size = be32(u8, pos);
      const fourcc = latin1(u8.subarray(pos + 4, pos + 8));
      let headerSize = 8;
      if (size === 1) {
        if (pos + 16 > end) break;
        size = be32(u8, pos + 8) * 4294967296 + be32(u8, pos + 12);
        headerSize = 16;
      } else if (size === 0) {
        size = end - pos;
      }
      if (size < headerSize || pos + size > end) break;
      boxes.push({ fourcc, payload: u8.subarray(pos + headerSize, pos + size), size, headerSize });
      pos += size;
    }
    return { boxes, scannedEnd: pos };
  }

  const isC2paBox = (fourcc) => fourcc === "jumb" || fourcc === "c2pa" || fourcc.toLowerCase().startsWith("c2");
  const isXmpUuid = (payload) => payload.length >= 16 && XMP_UUID.every((b, i) => payload[i] === b);

  function inspectIsobmff(u8, fmt, { byteScan = true } = {}) {
    const F = fmt.toUpperCase();
    const findings = [];
    let hasC2pa = false, hasAi = false;
    const { boxes } = parseIsobmffBoxes(u8);
    if (!boxes.length) {
      // Box parsing failed (typically the first box's size overruns a truncated
      // download), which is exactly when the whole-file byte scan is most
      // useful. Every sibling inspector still runs its equivalent after a
      // truncation, so run it here too and report the parse failure alongside
      // whatever it found (upstream #167).
      const whole = containsAny(u8, C2PA_MARKERS);
      if (whole.length) { hasC2pa = true; findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(", ")}`); }
      findings.push(`not a valid ${F} (no ISOBMFF boxes found)`);
      return { hasC2pa, hasAi: hasAi || hasC2pa, findings };
    }

    const strong = (hits, set) => hits.some((h) => set.has(h.toLowerCase()));

    for (const { fourcc, payload } of boxes) {
      if (isC2paBox(fourcc)) {
        hasC2pa = true;
        findings.push(`${F} top-level box ${fourcc} (C2PA/JUMBF manifest)`);
      } else if (fourcc === "uuid") {
        if (isXmpUuid(payload)) {
          hasAi = true;
          const hits = containsAny(payload.subarray(16), ALL_HINTS);
          findings.push(hits.length ? `${F} XMP uuid box: ${hits.slice(0, 8).join(", ")}` : `${F} XMP uuid box`);
          if (strong(hits, C2PA_STRONG)) hasC2pa = true;
        } else {
          const hits = containsAny(payload, ALL_HINTS);
          if (hits.length) {
            hasAi = true;
            findings.push(`${F} uuid box: ${hits.slice(0, 8).join(", ")}`);
            if (strong(hits, C2PA_STRONG_CORE)) hasC2pa = true;
          }
        }
      } else if (fourcc === "meta") {
        for (const sub of parseIsobmffBoxes(payload, 4).boxes) {
          const sName = sub.fourcc;
          if (isC2paBox(sName)) {
            hasC2pa = true;
            findings.push(`${F} meta sub-box ${sName} (C2PA/JUMBF container)`);
          } else if (sName === "uuid") {
            if (isXmpUuid(sub.payload)) {
              hasAi = true;
              const hits = containsAny(sub.payload.subarray(16), ALL_HINTS);
              findings.push(hits.length ? `${F} meta XMP uuid: ${hits.slice(0, 8).join(", ")}` : `${F} meta XMP uuid box`);
              if (strong(hits, C2PA_STRONG_CORE)) hasC2pa = true;
            } else {
              const hits = containsAny(sub.payload, ALL_HINTS);
              if (hits.length) { hasAi = true; findings.push(`${F} meta uuid: ${hits.slice(0, 8).join(", ")}`); }
            }
          } else if (["iinf", "infe", "iref", "iloc", "xml ", "bxml"].includes(sName)) {
            const hits = containsAny(sub.payload, ALL_HINTS);
            if (hits.length) {
              hasAi = true;
              if (strong(hits, C2PA_STRONG_CORE)) hasC2pa = true;
              findings.push(`${F} meta/${sName}: ${hits.slice(0, 8).join(", ")}`);
            }
          }
        }
      }
    }

    /* js/av_meta.js walks an MP4 box by box so a multi-gigabyte file never has
     * to be held in memory, and runs this scan once over the whole file in
     * chunks instead. Every other caller keeps it here. */
    if (byteScan) {
      const whole = containsAny(u8, C2PA_MARKERS);
      if (whole.length && !hasC2pa) { hasC2pa = true; findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(", ")}`); }
    }
    return { hasC2pa, hasAi: hasAi || hasC2pa, findings };
  }

  /* Serialize an ISOBMFF box, preserving the width of its original header so a
   * 64-bit box stays 64-bit and every later absolute offset keeps its meaning. */
  function buildIsobmffBox(fourcc, payload, headerSize = 8) {
    const size = payload.length + headerSize;
    const head = headerSize === 16
      ? packBe32(1).concat([...enc.encode(fourcc)], packU64(size, false))
      : packBe32(size).concat([...enc.encode(fourcc)]);
    return concat([new Uint8Array(head), payload]);
  }

  /* An equal-size `free` box to put where a dropped box used to be. Rewriting in
   * place instead of closing the gap is what keeps absolute media offsets valid
   * (upstream #183); the cleaned file therefore keeps its original length. */
  const isobmffFreeBox = (size, headerSize = 8) =>
    buildIsobmffBox("free", new Uint8Array(size - headerSize), headerSize);

  function stripIsobmff(u8, fmt, { stripAllMetadata = true } = {}) {
    const F = fmt.toUpperCase();
    const { boxes, scannedEnd } = parseIsobmffBoxes(u8);
    if (!boxes.length) throw new Error(`not a valid ${F} (no ISOBMFF boxes)`);
    // scannedEnd is where the box walk stopped: the parser halts at the first
    // box whose declared size overruns the data (a truncated download). The
    // rebuild below used to emit only the boxes that parsed, dropping a
    // truncated mdat (the actual coded image) while reporting "already clean"
    // (upstream #170); the tail is appended verbatim afterwards instead.
    const actions = [];
    const out = [];

    for (const { fourcc, payload, size, headerSize } of boxes) {
      if (isC2paBox(fourcc)) {
        actions.push(`drop top-level ${fourcc} box (C2PA/JUMBF)`);
        out.push(isobmffFreeBox(size, headerSize)); continue;
      }

      if (fourcc === "uuid") {
        if (isXmpUuid(payload)) {
          actions.push(`drop top-level ${fourcc} box (XMP metadata)`);
          out.push(isobmffFreeBox(size, headerSize)); continue;
        }
        if (stripAllMetadata || containsAny(payload, ALL_HINTS).length) {
          actions.push(`drop top-level ${fourcc} box (UUID metadata)`);
          out.push(isobmffFreeBox(size, headerSize)); continue;
        }
      }

      if (fourcc === "meta") {
        const verflags = payload.length >= 4 ? payload.subarray(0, 4) : new Uint8Array(4);
        const cleanSub = [];
        for (const sub of parseIsobmffBoxes(payload, 4).boxes) {
          const sName = sub.fourcc;
          if (isC2paBox(sName)) {
            actions.push(`drop meta sub-box ${sName} (C2PA/JUMBF)`);
            cleanSub.push(isobmffFreeBox(sub.size, sub.headerSize)); continue;
          }
          if (sName === "uuid") {
            if (isXmpUuid(sub.payload)) {
              actions.push(`drop meta sub-box ${sName} (XMP metadata)`);
              cleanSub.push(isobmffFreeBox(sub.size, sub.headerSize)); continue;
            }
            if (stripAllMetadata || containsAny(sub.payload, ALL_HINTS).length) {
              actions.push(`drop meta sub-box ${sName} (UUID metadata)`);
              cleanSub.push(isobmffFreeBox(sub.size, sub.headerSize)); continue;
            }
          }
          if (sName === "xml " || sName === "bxml") {
            if (stripAllMetadata || containsAny(sub.payload, ALL_HINTS).length) {
              actions.push(`drop meta sub-box ${sName} (XML metadata)`);
              cleanSub.push(isobmffFreeBox(sub.size, sub.headerSize)); continue;
            }
          }
          cleanSub.push(buildIsobmffBox(sName, sub.payload, sub.headerSize));
        }
        out.push(buildIsobmffBox("meta", concat([verflags, concat(cleanSub)]), headerSize));
        continue;
      }

      out.push(buildIsobmffBox(fourcc, payload, headerSize));
    }

    if (scannedEnd < u8.length) {
      const tail = u8.subarray(scannedEnd);
      out.push(tail);
      // An 8-byte header whose box overruns the data is a truncated download
      // worth reporting; fewer than 8 leftover bytes is merely trailing junk,
      // kept verbatim without claiming the file was truncated (upstream #170).
      if (tail.length >= 8) actions.push(`kept ${tail.length} bytes of truncated tail (file truncated)`);
    }

    if (!actions.length) actions.push(`no ${F} metadata boxes removed (already clean or none matched)`);
    return { data: concat(out), actions };
  }

  // ---------------------------------------------------------------- BMP
  /* BMP has no standardized metadata container. The only realistic place
   * provenance data can live is after the pixel payload, so the payload extent
   * is computed from the DIB header and pixel bytes are never scanned —
   * compressed or embedded-image data cannot false-positive. */
  function bmpPayloadExtent(u8) {
    if (u8.length < 30 || u8[0] !== 0x42 || u8[1] !== 0x4d) return null;
    const pixelOffset = le32(u8, 10);
    const dibSize = le32(u8, 14);
    if (dibSize < 40 || 14 + dibSize > u8.length) return null;
    const width = le32s(u8, 18);
    const height = le32s(u8, 22);
    const bpp = le16(u8, 28);
    const compression = le32(u8, 30);
    const sizeImage = le32(u8, 34);
    if (width <= 0 || bpp === 0 || pixelOffset > u8.length) return null;
    let size;
    if (compression === 0) {              // BI_RGB: rows padded to 4 bytes
      const rowSize = Math.floor((width * bpp + 31) / 32) * 4;
      size = rowSize * Math.abs(height);
    } else if (sizeImage) {
      size = sizeImage;
    } else {
      return null;                        // unparseable: stay conservative
    }
    return { pixelOffset, size };
  }

  function bmpTrailing(u8) {
    const extent = bmpPayloadExtent(u8);
    if (extent === null) return new Uint8Array(0);
    const end = extent.pixelOffset + extent.size;
    return end < u8.length ? u8.subarray(end) : new Uint8Array(0);
  }

  function inspectBmp(u8) {
    if (u8.length < 14 || u8[0] !== 0x42 || u8[1] !== 0x4d) {
      return { hasC2pa: false, hasAi: false, findings: ["not a BMP"] };
    }
    const findings = [];
    let hasC2pa = false, hasAi = false;
    const trailing = bmpTrailing(u8);
    if (trailing.length) {
      const hits = containsAny(trailing, ALL_HINTS);
      if (hits.length) {
        hasAi = true;
        if (hits.some((h) => C2PA_STRONG.has(h.toLowerCase()))) hasC2pa = true;
        findings.push(`BMP trailing metadata: ${hits.slice(0, 6).join(", ")}`);
      } else {
        findings.push(`BMP has ${trailing.length} unrecognized trailing byte(s)`);
      }
    } else {
      findings.push("BMP has no metadata (header-only raster format)");
    }
    return { hasC2pa, hasAi: hasAi || hasC2pa, findings };
  }

  function stripBmp(u8, { stripAllMetadata = true } = {}) {
    if (u8.length < 14 || u8[0] !== 0x42 || u8[1] !== 0x4d) throw new Error("not BMP");
    const extent = bmpPayloadExtent(u8);
    if (extent === null) return { data: u8, actions: ["BMP header not fully parsed; left unchanged"] };
    const end = extent.pixelOffset + extent.size;
    if (end >= u8.length) return { data: u8, actions: ["no BMP trailing metadata to strip"] };
    const trailing = u8.subarray(end);
    const hits = containsAny(trailing, ALL_HINTS);
    if (!stripAllMetadata && !hits.length) {
      return { data: u8, actions: ["BMP trailing bytes kept (keep-non-ai-metadata)"] };
    }
    const out = u8.slice(0, end);
    out.set(packLe32(end), 2);            // rewrite the file-size field
    const reason = hits.length ? ` (${hits.slice(0, 4).join(", ")})` : "";
    return { data: out, actions: [`drop ${trailing.length} BMP trailing byte(s)${reason}`] };
  }

  // ---------------------------------------------------------------- GIF
  const GIF_XMP_APPLICATION_ID = "XMP DataXMP";
  // Application extensions that control rendering rather than carrying
  // provenance; dropping them would change animation looping or color.
  const GIF_CONTROL_APPLICATION_IDS = ["NETSCAPE2.0", "ICCRGBG1012"];

  const isGif = (u8) => u8.length >= 6 && (latin1(u8.subarray(0, 6)) === "GIF87a" || latin1(u8.subarray(0, 6)) === "GIF89a");

  /** [end, label, payload] for the extension block at `start` (0x21), or null. */
  function gifExtensionInfo(u8, start, n) {
    if (start + 2 > n) return null;
    const label = u8[start + 1];
    let pos = start + 2;
    const parts = [];
    while (pos < n) {
      const size = u8[pos];
      pos += 1;
      if (size === 0) return { end: pos, label, payload: concat(parts) };
      if (pos + size > n) return null;
      parts.push(u8.subarray(pos, pos + size));
      pos += size;
    }
    return null;
  }

  /** Offset just past the image block starting at `start` (0x2C), or null. */
  function gifImageEnd(u8, start, n) {
    let pos = start + 1;
    if (pos + 9 > n) return null;
    const packed = u8[pos + 8];
    pos += 9;
    if (packed & 0x80) pos += 3 * (1 << ((packed & 0x07) + 1));  // local color table
    if (pos >= n) return null;
    pos += 1;                                                     // LZW minimum code size
    while (pos < n) {
      const size = u8[pos];
      pos += 1;
      if (size === 0) return pos;
      if (pos + size > n) return null;
      pos += size;
    }
    return null;
  }

  function inspectGif(u8) {
    if (!isGif(u8)) return { hasC2pa: false, hasAi: false, findings: ["not a GIF"] };
    const findings = [];
    let hasC2pa = false, hasAi = false;
    const n = u8.length;
    let pos = 6;
    if (pos + 7 > n) return { hasC2pa: false, hasAi: false, findings: ["truncated GIF header"] };
    const packed = u8[pos + 4];
    pos += 7;
    if (packed & 0x80) pos += 3 * (1 << ((packed & 0x07) + 1));   // global color table
    while (pos < n) {
      const block = u8[pos];
      if (block === 0x3b) break;                                  // trailer
      if (block === 0x21) {
        const info = gifExtensionInfo(u8, pos, n);
        if (info === null) { findings.push("truncated GIF extension"); break; }
        const { end, label, payload } = info;
        if (label === 0xfe) {
          findings.push("GIF comment extension present");
          const hits = containsAny(payload, ALL_HINTS);
          if (hits.length) { hasAi = true; findings.push(`GIF comment: ${hits.slice(0, 6).join(", ")}`); }
        } else if (label === 0xff) {
          const ident = latin1(payload.subarray(0, 11));
          if (ident === GIF_XMP_APPLICATION_ID) {
            findings.push("GIF XMP application extension present");
            const hits = containsAny(payload, ALL_HINTS);
            if (hits.length) { hasAi = true; findings.push(`GIF XMP: ${hits.slice(0, 6).join(", ")}`); }
          } else if (["c2pa", "jumb", "C2PA", "JUMB"].some((m) => ident.includes(m))) {
            hasC2pa = true;
            findings.push("GIF application extension (possible C2PA)");
          }
        }
        pos = end;
      } else if (block === 0x2c) {
        const end = gifImageEnd(u8, pos, n);
        if (end === null) { findings.push("truncated GIF image block"); break; }
        pos = end;
      } else {
        pos += 1;
      }
    }
    const whole = containsAny(u8, C2PA_MARKERS);
    if (whole.length && !hasC2pa) {
      hasC2pa = true;
      findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(", ")}`);
    }
    if (!findings.length) findings.push("no GIF metadata extensions found");
    return { hasC2pa, hasAi: hasAi || hasC2pa, findings };
  }

  function stripGif(u8, { stripAllMetadata = true } = {}) {
    if (!isGif(u8)) throw new Error("not GIF");
    const actions = [];
    const parts = [u8.subarray(0, 6)];
    const n = u8.length;
    let pos = 6;
    if (pos + 7 > n) throw new Error("truncated GIF header");
    const packed = u8[pos + 4];
    parts.push(u8.subarray(pos, pos + 7));
    pos += 7;
    if (packed & 0x80) {
      const gctSize = 3 * (1 << ((packed & 0x07) + 1));
      parts.push(u8.subarray(pos, pos + gctSize));
      pos += gctSize;
    }
    while (pos < n) {
      const block = u8[pos];
      if (block === 0x3b) { parts.push(u8.subarray(pos)); break; }   // trailer
      if (block === 0x21) {
        const info = gifExtensionInfo(u8, pos, n);
        if (info === null) { parts.push(u8.subarray(pos)); break; }
        const { end, label, payload } = info;
        let drop = false, name = "extension";
        if (label === 0xfe) {
          name = "comment";
          drop = stripAllMetadata || containsAny(payload, ALL_HINTS).length > 0;
        } else if (label === 0xff) {
          const ident = latin1(payload.subarray(0, 11));
          const markerHit = containsAny(payload, ALL_HINTS).length > 0;
          if (ident === GIF_XMP_APPLICATION_ID) {
            name = "XMP application";
            drop = stripAllMetadata || markerHit;
          } else if (GIF_CONTROL_APPLICATION_IDS.includes(ident)) {
            name = "control application";
            drop = markerHit;                 // keep looping/ICC unless it carries markers
          } else {
            name = "application";
            drop = stripAllMetadata || markerHit;
          }
        }
        if (drop) actions.push(`drop GIF ${name} extension`);
        else parts.push(u8.subarray(pos, end));
        pos = end;
      } else if (block === 0x2c) {
        const end = gifImageEnd(u8, pos, n);
        if (end === null) { parts.push(u8.subarray(pos)); break; }
        parts.push(u8.subarray(pos, end));
        pos = end;
      } else {
        parts.push(u8.subarray(pos, pos + 1));
        pos += 1;
      }
    }
    if (!actions.length) actions.push("no GIF metadata blocks removed (already clean or none matched)");
    return { data: concat(parts), actions };
  }

  // ---------------------------------------------------------------- TIFF (classic + BigTIFF)
  const TIFF_TYPE_SIZES = { 1: 1, 2: 1, 3: 2, 4: 4, 5: 8, 6: 1, 7: 1, 8: 2, 9: 4, 10: 8, 11: 4, 12: 8 };

  // Provenance / descriptive metadata tags stripped when cleaning TIFF.
  const TIFF_META_TAG_NAMES = {
    269: "DocumentName", 270: "ImageDescription", 271: "Make", 272: "Model", 305: "Software",
    306: "DateTime", 315: "Artist", 316: "HostComputer", 33432: "Copyright", 40091: "XPTitle",
    40092: "XPComment", 40093: "XPAuthor", 40094: "XPKeywords", 40095: "XPSubject", 700: "XMP",
    33723: "IPTC/NAA", 34377: "Photoshop", 34665: "ExifIFD", 34853: "GPSInfo", 37500: "MakerNote",
  };
  const TIFF_DROP_TAGS = new Set(Object.keys(TIFF_META_TAG_NAMES).map(Number));

  // Structural tags that must survive even when their payload looks marker-ish
  // (offset lists, color tables, compression tables, DNG core tags).
  const TIFF_KEEP_TAGS = new Set([
    254, 255, 256, 257, 258, 259, 262, 263, 264, 265, 266, 273, 274, 277, 278, 279, 282, 283, 284,
    285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 301, 302, 304, 320, 321, 322,
    323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 336, 338, 339, 340, 341, 342, 343,
    344, 345, 346, 347, 512, 513, 514, 515, 517, 518, 519, 520, 521, 529, 530, 531, 532, 33421,
    33422, 33423, 50706, 50707, 50708, 50709, 50710, 50711, 50712, 50713, 50714, 50715, 50716,
    50717, 50718, 50719, 50720, 50721, 50722, 50723, 50724, 50725, 50726, 50727, 50728, 50729,
    50730, 50731, 50732, 50733, 50734, 50735, 50736, 50737, 50738, 50739, 50740, 50741,
  ]);
  const TIFF_SUB_IFD_TAGS = [34665, 34853, 40965];
  const MAX_TIFF_IFDS = 4096;

  /** {le, bigtiff} for a classic or BigTIFF header, else null. */
  // Compared as bytes, not latin-1 text: two of the four signatures contain a
  // NUL, which has no business being written into a source file.
  const TIFF_SIGS = [
    { sig: [0x49, 0x49, 0x2a, 0x00], le: true, bigtiff: false },   // II*\0
    { sig: [0x4d, 0x4d, 0x00, 0x2a], le: false, bigtiff: false },  // MM\0*
    { sig: [0x49, 0x49, 0x2b, 0x00], le: true, bigtiff: true },    // II+\0  BigTIFF
    { sig: [0x4d, 0x4d, 0x00, 0x2b], le: false, bigtiff: true },   // MM\0+  BigTIFF
  ];

  function tiffLayout(u8) {
    if (u8.length < 4) return null;
    for (const c of TIFF_SIGS) {
      if (c.sig.every((b, i) => u8[i] === b)) return { le: c.le, bigtiff: c.bigtiff };
    }
    return null;
  }

  /* Parse every reachable IFD. Entries carry the raw inline field bytes so a
   * kept entry can be written back byte-identically; valueOffset is null when
   * the value fits inline. Cycle-protected with a hard cap. */
  function parseTiffIfds(u8) {
    const layout = tiffLayout(u8);
    if (layout === null) throw new Error("not a TIFF");
    const { le, bigtiff } = layout;
    const n = u8.length;
    const countLen = bigtiff ? 8 : 2;
    const offLen = bigtiff ? 8 : 4;
    const entrySize = bigtiff ? 20 : 12;
    const headerSize = bigtiff ? 16 : 8;
    const readCount = (p) => (bigtiff ? u64at(u8, p, le) : u16at(u8, p, le));
    const readOff = (p) => (bigtiff ? u64at(u8, p, le) : u32at(u8, p, le));
    const ifds = new Map();
    if (n < headerSize) return { le, bigtiff, ifds };
    const first = readOff(headerSize - offLen);
    if (first === 0 || first + countLen > n) return { le, bigtiff, ifds };
    const seen = new Set();
    const todo = [first];
    while (todo.length && ifds.size < MAX_TIFF_IFDS) {
      const off = todo.pop();
      if (seen.has(off) || off + countLen > n) continue;
      seen.add(off);
      const count = readCount(off);
      let blockLen = countLen + count * entrySize;
      let nextPtr;
      if (off + blockLen + offLen <= n) {
        nextPtr = readOff(off + blockLen);
      } else {
        blockLen = Math.max(0, n - off - offLen);
        nextPtr = 0;
      }
      const entries = [];
      for (let i = 0; i < count; i++) {
        const e = off + countLen + i * entrySize;
        if (e + entrySize > n) break;
        const tag = u16at(u8, e, le);
        const ftype = u16at(u8, e + 2, le);
        const fcount = bigtiff ? u64at(u8, e + 4, le) : u32at(u8, e + 4, le);
        const value = u8.subarray(e + 4 + offLen, e + entrySize);
        const byteSize = fcount * (TIFF_TYPE_SIZES[ftype] || 1);
        const valueOffset = byteSize > value.length
          ? (bigtiff ? u64at(value, 0, le) : u32at(value, 0, le))
          : null;
        entries.push({ tag, type: ftype, count: fcount, value, byteSize, valueOffset });
      }
      ifds.set(off, { count, entries, next: nextPtr, blockLen });
      if (nextPtr) todo.push(nextPtr);
      for (const ent of entries) {
        if (ent.tag === 34665 || ent.tag === 34853 || ent.tag === 40965) {
          const ptr = bigtiff ? u64at(ent.value, 0, le) : u32at(ent.value, 0, le);
          if (ptr) todo.push(ptr);
        }
      }
    }
    return { le, bigtiff, ifds };
  }

  function tiffEntryPayload(u8, ent) {
    if (ent.valueOffset === null) {
      return ent.byteSize <= ent.value.length ? ent.value.subarray(0, ent.byteSize) : null;
    }
    return u8.subarray(ent.valueOffset, ent.valueOffset + ent.byteSize);
  }

  const sortedOffsets = (ifds) => Array.from(ifds.keys()).sort((a, b) => a - b);

  function inspectTiff(u8) {
    const findings = [];
    let hasC2pa = false, hasAi = false;
    let parsed;
    try {
      parsed = parseTiffIfds(u8);
    } catch (_) {
      return { hasC2pa: false, hasAi: false, findings: ["not a valid TIFF"] };
    }
    const { ifds } = parsed;
    if (!ifds.size) return { hasC2pa: false, hasAi: false, findings: ["TIFF with no image file directories"] };
    for (const off of sortedOffsets(ifds)) {
      for (const ent of ifds.get(off).entries) {
        const payload = tiffEntryPayload(u8, ent);
        const hits = containsAny(payload || new Uint8Array(0), ALL_HINTS);
        if (hits.length) {
          if (hits.some((h) => C2PA_STRONG.has(h.toLowerCase()))) hasC2pa = true;
          hasAi = true;
          findings.push(`TIFF tag ${ent.tag}: ${hits.slice(0, 6).join(", ")}`);
        }
        const name = TIFF_META_TAG_NAMES[ent.tag];
        if (name) {
          const label = TIFF_SUB_IFD_TAGS.includes(ent.tag) ? "sub-IFD" : "tag";
          findings.push(`TIFF ${label} ${ent.tag} (${name}) present`);
        }
      }
    }
    const whole = containsAny(u8, C2PA_MARKERS);
    if (whole.length && !hasC2pa) {
      hasC2pa = true;
      findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(", ")}`);
    }
    if (!findings.length) findings.push("no TIFF metadata tags found");
    return { hasC2pa, hasAi: hasAi || hasC2pa, findings };
  }

  /* Drop metadata tags without moving referenced data: each IFD entry region is
   * patched in place and zero-padded back to its original length, so strip/tile
   * offsets, color tables and next-IFD pointers all stay valid. */
  function stripTiff(u8, { stripAllMetadata = true } = {}) {
    const { le, bigtiff, ifds } = parseTiffIfds(u8);
    if (!ifds.size) throw new Error("not a valid TIFF (no image file directories)");
    const n = u8.length;
    const offLen = bigtiff ? 8 : 4;
    const readPtr = (v) => (bigtiff ? u64at(v, 0, le) : u32at(v, 0, le));
    const packOff = (v) => (bigtiff ? packU64(v, le) : packU32(v, le));
    const packCount = (v) => (bigtiff ? packU64(v, le) : packU16(v, le));
    const actions = [];
    const kept = new Map();
    const dropRanges = [];
    const dropIfdRanges = [];

    /** Record the region and value payloads of a dropped sub-IFD chain. */
    function collectSubIfdDrops(ptr, seen) {
      const sub = ifds.get(ptr);
      if (sub === undefined || seen.has(ptr)) return;
      seen.add(ptr);
      dropIfdRanges.push([ptr, Math.min(ptr + sub.blockLen + offLen, n)]);
      for (const ent of sub.entries) {
        if (ent.tag === 34665 || ent.tag === 34853) {
          const p2 = readPtr(ent.value);
          if (p2) collectSubIfdDrops(p2, seen);
        } else if (ent.valueOffset !== null) {
          if (ent.valueOffset + ent.byteSize <= n) dropRanges.push([ent.valueOffset, ent.valueOffset + ent.byteSize]);
        }
      }
    }

    for (const off of sortedOffsets(ifds)) {
      const keepHere = [];
      for (const ent of ifds.get(off).entries) {
        const tag = ent.tag;
        const payload = tiffEntryPayload(u8, ent);
        let markerHit = containsAny(payload || new Uint8Array(0), ALL_HINTS).length > 0;
        if (tag === 34665 || tag === 34853) {
          const ptr = readPtr(ent.value);
          const sub = ifds.get(ptr);
          if (sub !== undefined) {
            const subBlob = u8.subarray(ptr, Math.min(ptr + sub.blockLen + offLen, n));
            markerHit = markerHit || containsAny(subBlob, ALL_HINTS).length > 0;
            for (const sent of sub.entries) {
              const sPayload = tiffEntryPayload(u8, sent);
              if (containsAny(sPayload || new Uint8Array(0), ALL_HINTS).length) { markerHit = true; break; }
            }
          }
        }
        let drop = false;
        if (TIFF_DROP_TAGS.has(tag)) drop = stripAllMetadata || markerHit;
        else if (markerHit && !TIFF_KEEP_TAGS.has(tag)) drop = true;
        if (!drop) { keepHere.push(ent); continue; }
        const name = TIFF_META_TAG_NAMES[tag];
        actions.push(name ? `drop TIFF tag ${tag} (${name})` : `drop TIFF tag ${tag} (AI markers)`);
        if (tag === 34665 || tag === 34853) {
          collectSubIfdDrops(readPtr(ent.value), new Set());
        } else if (ent.valueOffset !== null && ent.valueOffset + ent.byteSize <= n) {
          dropRanges.push([ent.valueOffset, ent.valueOffset + ent.byteSize]);
        }
      }
      kept.set(off, keepHere);
    }

    // Ranges still reachable from the root through kept entries must never be
    // zeroed. An orphaned sub-IFD (its pointer dropped) contributes nothing.
    const reachable = new Set();
    function markReachable(off) {
      if (reachable.has(off) || !ifds.has(off)) return;
      reachable.add(off);
      for (const ent of kept.get(off) || []) {
        if (TIFF_SUB_IFD_TAGS.includes(ent.tag)) markReachable(readPtr(ent.value));
      }
      if (ifds.get(off).next) markReachable(ifds.get(off).next);
    }
    markReachable(bigtiff ? u64at(u8, 8, le) : u32at(u8, 4, le));

    const referenced = [];
    for (const off of Array.from(reachable).sort((a, b) => a - b)) {
      for (const ent of kept.get(off) || []) {
        if (ent.valueOffset !== null && ent.valueOffset + ent.byteSize <= n) {
          referenced.push([ent.valueOffset, ent.valueOffset + ent.byteSize]);
        }
        if (TIFF_SUB_IFD_TAGS.includes(ent.tag)) {
          const ptr = readPtr(ent.value);
          const sub = ifds.get(ptr);
          if (sub !== undefined) referenced.push([ptr, Math.min(ptr + sub.blockLen + offLen, n)]);
        }
      }
    }
    const covered = (ranges, start, end) => ranges.some(([s, e]) => s <= start && end <= e);
    const zero = [];
    for (const [s, e] of dropRanges) if (!covered(referenced, s, e)) zero.push([s, e]);
    for (const [s, e] of dropIfdRanges) if (!covered(referenced, s, e)) zero.push([s, e]);

    // Patch IFD entry regions in place, then zero dropped payloads.
    const out = u8.slice();
    for (const off of sortedOffsets(ifds)) {
      const ifd = ifds.get(off);
      const entries = kept.get(off) || [];
      const blockParts = [new Uint8Array(packCount(entries.length))];
      for (const ent of entries) {
        blockParts.push(new Uint8Array(packU16(ent.tag, le)));
        blockParts.push(new Uint8Array(packU16(ent.type, le)));
        blockParts.push(new Uint8Array(packOff(ent.count)));
        blockParts.push(ent.value);
      }
      blockParts.push(new Uint8Array(packOff(ifd.next)));
      let block = concat(blockParts);
      const regionLen = ifd.blockLen + offLen;
      if (off + regionLen <= n) {
        if (block.length > regionLen) block = block.subarray(0, regionLen);
        out.set(block, off);
        out.fill(0, off + block.length, off + regionLen);
      }
    }
    for (const [s, e] of zero) out.fill(0, s, e);

    if (!actions.length) actions.push("no TIFF metadata tags removed (already clean or none matched)");
    return { data: out, actions };
  }

  // ---------------------------------------------------------------- unified
  function inspect(u8) {
    const fmt = detectFormat(u8);
    const r = fmt === "png" ? inspectPng(u8) : fmt === "jpeg" ? inspectJpeg(u8) : fmt === "webp" ? inspectWebp(u8)
      : (fmt === "avif" || fmt === "heic") ? inspectIsobmff(u8, fmt)
      : fmt === "bmp" ? inspectBmp(u8) : fmt === "gif" ? inspectGif(u8) : fmt === "tiff" ? inspectTiff(u8)
      : { hasC2pa: false, hasAi: false, findings: ["unsupported format (PNG/JPEG/WebP/AVIF/HEIC/BMP/GIF/TIFF)"] };
    return { format: fmt, has_c2pa: r.hasC2pa, has_ai_metadata: r.hasAi, findings: r.findings };
  }

  /** clean(u8, {stripAllMetadata}) -> {format, data, actions} ; throws on unsupported/malformed. */
  function clean(u8, { stripAllMetadata = true } = {}) {
    const fmt = detectFormat(u8);
    if (fmt === "png") return { format: fmt, ...stripPng(u8, { stripAllText: stripAllMetadata }) };
    if (fmt === "jpeg") return { format: fmt, ...stripJpeg(u8, { stripAllApp: stripAllMetadata }) };
    if (fmt === "webp") return { format: fmt, ...stripWebp(u8, { stripAllMetadata }) };
    if (fmt === "avif" || fmt === "heic") return { format: fmt, ...stripIsobmff(u8, fmt, { stripAllMetadata }) };
    if (fmt === "bmp") return { format: fmt, ...stripBmp(u8, { stripAllMetadata }) };
    if (fmt === "gif") return { format: fmt, ...stripGif(u8, { stripAllMetadata }) };
    if (fmt === "tiff") return { format: fmt, ...stripTiff(u8, { stripAllMetadata }) };
    throw new Error("unsupported image format (expected PNG, JPEG, WebP, AVIF, HEIC, BMP, GIF or TIFF)");
  }

  /* AI_META_HINTS, C2PA_MARKERS and the four ISOBMFF primitives are exported for
   * js/av_meta.js, mirroring what upstream's av_meta.py imports from
   * image_meta.py. Audio and video reuse this box walker rather than carrying a
   * second one. */
  const api = { detectFormat, inspect, clean, inspectPng, inspectJpeg, inspectWebp, inspectIsobmff,
    inspectBmp, inspectGif, inspectTiff,
    stripPng, stripJpeg, stripWebp, stripIsobmff, stripBmp, stripGif, stripTiff, containsAny,
    parseIsobmffBoxes, buildIsobmffBox, isobmffFreeBox, AI_META_HINTS, C2PA_MARKERS };
  root.ImageMeta = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof globalThis !== "undefined" ? globalThis : this);
