/*
 * Detect and strip C2PA / AI-related metadata from PNG, JPEG and WebP.
 *
 * JavaScript port of the stdlib parsers in `service/scripts/image_meta.py`
 * from guillaumemeyer/watermarks-remover (MIT): same chunk/segment policy,
 * same marker heuristics, same VP8X flag fix-up. Pixels are never touched —
 * this is byte-level container surgery, not a canvas re-encode.
 *
 * Works as a plain <script> (window.ImageMeta) and as a CommonJS module.
 */
(function (root) {
  "use strict";

  const enc = new TextEncoder();
  const PNG_SIG = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

  const C2PA_MARKERS = ["c2pa", "C2PA", "jumb", "JUMB", "c2ma", "contentcredentials", "contentauth", "cai:",
    "http://ns.adobe.com/xmp/InstanceID/"];
  const AI_META_HINTS = ["c2pa", "C2PA", "contentcredentials", "ContentCredentials", "digitalSourceType",
    "trainedAlgorithmicMedia", "compositeWithTrainedAlgorithmicMedia", "algorithmicMedia", "AIGC", "aigc",
    "AI generated", "Generated by", "Claude", "Anthropic", "OpenAI", "SynthID", "dcterms:provenance"];
  const ALL_HINTS = AI_META_HINTS.concat(C2PA_MARKERS);
  const C2PA_STRONG = new Set(["c2pa", "contentcredentials", "jumb", "contentauth"]);
  const C2PA_STRONG_PNG = new Set(["c2pa", "contentcredentials", "jumb"]);

  const latin1 = (u8) => { let s = ""; for (let i = 0; i < u8.length; i++) s += String.fromCharCode(u8[i]); return s; };
  const startsWith = (u8, sig) => sig.every((b, i) => u8[i] === b);
  const be32 = (u8, p) => ((u8[p] << 24) | (u8[p + 1] << 16) | (u8[p + 2] << 8) | u8[p + 3]) >>> 0;
  const be16 = (u8, p) => (u8[p] << 8) | u8[p + 1];
  const le32 = (u8, p) => (u8[p] | (u8[p + 1] << 8) | (u8[p + 2] << 16) | (u8[p + 3] << 24)) >>> 0;
  const packLe32 = (n) => [n & 0xff, (n >>> 8) & 0xff, (n >>> 16) & 0xff, (n >>> 24) & 0xff];

  /** Case-insensitive substring scan of a byte blob (latin-1 view), like upstream _contains_any. */
  function containsAny(u8, needles) {
    const lower = latin1(u8).toLowerCase();
    const found = [];
    for (const n of needles) if (lower.includes(n.toLowerCase())) found.push(n);
    return found;
  }

  function detectFormat(u8) {
    if (u8.length >= 8 && startsWith(u8, PNG_SIG)) return "png";
    if (u8.length >= 2 && u8[0] === 0xff && u8[1] === 0xd8) return "jpeg";
    if (u8.length >= 12 && latin1(u8.subarray(0, 4)) === "RIFF" && latin1(u8.subarray(8, 12)) === "WEBP") return "webp";
    return "unknown";
  }

  function concat(parts) {
    let n = 0; for (const p of parts) n += p.length;
    const out = new Uint8Array(n); let o = 0;
    for (const p of parts) { out.set(p, o); o += p.length; }
    return out;
  }

  // ---------------------------------------------------------------- PNG
  function* pngChunks(u8) {
    let pos = 8;
    while (pos + 8 <= u8.length) {
      const length = be32(u8, pos);
      const type = latin1(u8.subarray(pos + 4, pos + 8));
      const start = pos + 8, end = start + length;
      if (end + 4 > u8.length) { yield { type, truncated: true }; return; }
      yield { type, payload: u8.subarray(start, end), raw: u8.subarray(pos, end + 4) };
      if (type === "IEND") return;
      pos = end + 4;
    }
  }

  function inspectPng(u8) {
    const findings = []; let hasC2pa = false, hasAi = false;
    if (detectFormat(u8) !== "png") return { hasC2pa: false, hasAi: false, findings: ["not a PNG"] };
    for (const c of pngChunks(u8)) {
      if (c.truncated) { findings.push(`truncated chunk ${c.type}`); break; }
      if (c.type === "caBX" || c.type === "juMB" || c.type === "jumb" || c.type.startsWith("c2")) {
        hasC2pa = true; findings.push(`PNG chunk ${c.type} (possible C2PA container)`);
      }
      if (["tEXt", "zTXt", "iTXt", "eXIf"].includes(c.type)) {
        const hits = containsAny(c.payload, ALL_HINTS);
        if (hits.length) {
          hasAi = true;
          if (hits.some((h) => C2PA_STRONG_PNG.has(h.toLowerCase()))) hasC2pa = true;
          findings.push(`PNG ${c.type}: ${hits.slice(0, 8).join(", ")}`);
        }
      }
    }
    const whole = containsAny(u8, C2PA_MARKERS);
    if (whole.length && !hasC2pa) { hasC2pa = true; findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(", ")}`); }
    return { hasC2pa, hasAi: hasAi || hasC2pa, findings };
  }

  const PNG_STRUCTURAL = new Set(["IHDR", "IDAT", "IEND", "PLTE", "tRNS", "gAMA", "pHYs", "sRGB", "cHRM", "iCCP"]);

  function stripPng(u8, { stripAllText = true } = {}) {
    if (detectFormat(u8) !== "png") throw new Error("not PNG");
    const actions = []; const out = [new Uint8Array(PNG_SIG)];
    for (const c of pngChunks(u8)) {
      if (c.truncated) break;
      let drop = false;
      if (c.type === "eXIf" || c.type === "caBX" || c.type.startsWith("c2")) {
        drop = true; actions.push(`drop chunk ${c.type}`);
      } else if (["tEXt", "zTXt", "iTXt"].includes(c.type)) {
        if (stripAllText || containsAny(c.payload, ALL_HINTS).length) { drop = true; actions.push(`drop chunk ${c.type}`); }
      } else if (!PNG_STRUCTURAL.has(c.type) && containsAny(concat([enc.encode(c.type), c.payload]), C2PA_MARKERS).length) {
        drop = true; actions.push(`drop chunk ${c.type} (C2PA marker in payload)`);
      }
      if (!drop) out.push(c.raw);
    }
    if (!actions.length) actions.push("no PNG metadata chunks removed (already clean or none matched)");
    return { data: concat(out), actions };
  }

  // ---------------------------------------------------------------- JPEG
  function inspectJpeg(u8) {
    const findings = []; let hasC2pa = false, hasAi = false;
    if (detectFormat(u8) !== "jpeg") return { hasC2pa: false, hasAi: false, findings: ["not a JPEG"] };
    let i = 2; const n = u8.length;
    while (i + 4 <= n) {
      if (u8[i] !== 0xff) { i++; continue; }
      while (i < n && u8[i] === 0xff) i++;
      if (i >= n) break;
      const marker = u8[i]; i++;
      if (marker === 0xd8 || marker === 0xd9) continue;
      if (marker === 0xda) break;
      if (marker >= 0xd0 && marker <= 0xd7) continue;
      if (i + 2 > n) break;
      const seglen = be16(u8, i);
      if (seglen < 2 || i + seglen > n) { findings.push(`bad segment length at marker 0x${marker.toString(16).toUpperCase()}`); break; }
      const payload = u8.subarray(i + 2, i + seglen); i += seglen;
      if (marker === 0xeb) { hasC2pa = true; findings.push("JPEG APP11 segment (JUMBF/C2PA common)"); }
      if ([0xe1, 0xe2, 0xed, 0xee, 0xeb].includes(marker)) {
        const hits = containsAny(payload, ALL_HINTS);
        if (hits.length) {
          hasAi = true;
          if (hits.some((h) => C2PA_STRONG.has(h.toLowerCase()))) hasC2pa = true;
          findings.push(`JPEG APP${marker - 0xe0}: ${hits.slice(0, 8).join(", ")}`);
        }
      }
    }
    const whole = containsAny(u8, C2PA_MARKERS);
    if (whole.length && !hasC2pa) { hasC2pa = true; findings.push(`byte-scan C2PA markers: ${whole.slice(0, 6).join(", ")}`); }
    return { hasC2pa, hasAi: hasAi || hasC2pa, findings };
  }

  function stripJpeg(u8, { stripAllApp = true } = {}) {
    if (detectFormat(u8) !== "jpeg") throw new Error("not JPEG");
    const actions = []; const out = [new Uint8Array([0xff, 0xd8])];
    let i = 2; const n = u8.length;
    while (i < n) {
      if (u8[i] !== 0xff) { out.push(u8.subarray(i)); actions.push("copied remainder after non-marker byte"); break; }
      while (i < n && u8[i] === 0xff) i++;
      if (i >= n) break;
      const marker = u8[i]; i++;
      if (marker === 0xd9) { out.push(new Uint8Array([0xff, 0xd9])); break; }
      if (marker === 0xd8) continue;
      if (marker >= 0xd0 && marker <= 0xd7) { out.push(new Uint8Array([0xff, marker])); continue; }
      if (marker === 0xda) {
        if (i + 2 > n) break;
        out.push(new Uint8Array([0xff, 0xda])); out.push(u8.subarray(i));
        actions.push("preserved entropy-coded scan (SOS→EOF)");
        break;
      }
      if (i + 2 > n) break;
      const seglen = be16(u8, i);
      if (seglen < 2 || i + seglen > n) { out.push(u8.subarray(i - 2)); actions.push("truncated segment; copied remainder"); break; }
      const payload = u8.subarray(i + 2, i + seglen);
      let keep = false, drop = false;
      if (marker >= 0xe0 && marker <= 0xef) {
        if (marker === 0xeb) { drop = true; actions.push("drop APP11 (C2PA/JUMBF)"); }
        else if (stripAllApp && marker !== 0xe0) { drop = true; actions.push(`drop APP${marker - 0xe0}`); }
        else if (containsAny(payload, ALL_HINTS).length) { drop = true; actions.push(`drop APP${marker - 0xe0} (AI/C2PA markers)`); }
        else keep = true;
      } else if (marker === 0xfe) { drop = true; actions.push("drop COM comment"); }
      else keep = true;
      if (keep && !drop) { out.push(new Uint8Array([0xff, marker])); out.push(u8.subarray(i, i + seglen)); }
      i += seglen;
    }
    if (!actions.length) actions.push("no JPEG APP segments removed");
    return { data: concat(out), actions };
  }

  // ---------------------------------------------------------------- WebP
  function webpChunks(u8) {
    if (detectFormat(u8) !== "webp") return { chunks: [], notes: ["not a WebP"] };
    const notes = [];
    const declared = le32(u8, 4);
    if (declared + 8 !== u8.length) notes.push(`RIFF size mismatch: header=${declared + 8} actual=${u8.length}`);
    const chunks = []; let pos = 12;
    while (pos + 8 <= u8.length) {
      const fourcc = latin1(u8.subarray(pos, pos + 4));
      const length = le32(u8, pos + 4);
      const ps = pos + 8, pe = ps + length, padded = pe + (length & 1);
      if (padded > u8.length) { notes.push(`truncated WebP chunk ${fourcc}`); break; }
      chunks.push({ fourcc, payload: u8.subarray(ps, pe), padding: u8.subarray(pe, padded) });
      pos = padded;
    }
    if (pos !== u8.length && !notes.some((x) => x.includes("truncated"))) notes.push(`trailing WebP bytes: ${u8.length - pos}`);
    return { chunks, notes };
  }

  function inspectWebp(u8) {
    const { chunks, notes } = webpChunks(u8);
    const findings = notes.slice();
    if (!chunks.length && notes[0] === "not a WebP") return { hasC2pa: false, hasAi: false, findings };
    let hasC2pa = false, hasAi = false;
    for (const c of chunks) {
      if (c.fourcc.toUpperCase() === "C2PA") { hasC2pa = true; hasAi = true; findings.push("WebP C2PA chunk"); continue; }
      if (c.fourcc === "XMP " || c.fourcc === "EXIF") {
        const hits = containsAny(c.payload, ALL_HINTS);
        if (hits.length) {
          hasAi = true;
          if (hits.some((h) => C2PA_STRONG.has(h.toLowerCase()))) hasC2pa = true;
          findings.push(`WebP ${c.fourcc}: ${hits.slice(0, 8).join(", ")}`);
        }
      }
    }
    return { hasC2pa, hasAi: hasAi || hasC2pa, findings };
  }

  const WEBP_META_FLAGS = { ICCP: 0x20, EXIF: 0x08, "XMP ": 0x04 };

  function stripWebp(u8, { stripAllMetadata = true } = {}) {
    const { chunks, notes } = webpChunks(u8);
    if (!chunks.length && notes[0] === "not a WebP") throw new Error("not WebP");
    if (notes.length) throw new Error("malformed WebP: " + notes.join("; "));
    const actions = []; const kept = []; let removedFlags = 0;
    for (const c of chunks) {
      let drop = c.fourcc.toUpperCase() === "C2PA";
      if (c.fourcc in WEBP_META_FLAGS) drop = stripAllMetadata || containsAny(c.payload, ALL_HINTS).length > 0;
      if (drop) { actions.push(`drop WebP chunk ${c.fourcc}`); removedFlags |= WEBP_META_FLAGS[c.fourcc] || 0; }
      else kept.push(c);
    }
    const body = [enc.encode("WEBP")];
    for (const c of kept) {
      let payload = c.payload;
      if (c.fourcc === "VP8X" && payload.length >= 1 && removedFlags) {
        payload = new Uint8Array(payload); payload[0] &= ~removedFlags;
      }
      body.push(enc.encode(c.fourcc), new Uint8Array(packLe32(payload.length)), payload);
      if (payload.length & 1) body.push(c.padding.length ? c.padding : new Uint8Array([0]));
    }
    const bodyBytes = concat(body);
    if (!actions.length) actions.push("no WebP metadata chunks removed (already clean or none matched)");
    return { data: concat([enc.encode("RIFF"), new Uint8Array(packLe32(bodyBytes.length)), bodyBytes]), actions };
  }

  // ---------------------------------------------------------------- unified
  function inspect(u8) {
    const fmt = detectFormat(u8);
    const r = fmt === "png" ? inspectPng(u8) : fmt === "jpeg" ? inspectJpeg(u8) : fmt === "webp" ? inspectWebp(u8)
      : { hasC2pa: false, hasAi: false, findings: ["unsupported image format"] };
    return { format: fmt, has_c2pa: r.hasC2pa, has_ai_metadata: r.hasAi, findings: r.findings };
  }

  /** clean(u8, {stripAllMetadata}) -> {format, data, actions} ; throws on unsupported/malformed. */
  function clean(u8, { stripAllMetadata = true } = {}) {
    const fmt = detectFormat(u8);
    if (fmt === "png") return { format: fmt, ...stripPng(u8, { stripAllText: stripAllMetadata }) };
    if (fmt === "jpeg") return { format: fmt, ...stripJpeg(u8, { stripAllApp: stripAllMetadata }) };
    if (fmt === "webp") return { format: fmt, ...stripWebp(u8, { stripAllMetadata }) };
    throw new Error("unsupported image format (expected PNG, JPEG or WebP)");
  }

  const api = { detectFormat, inspect, clean, inspectPng, inspectJpeg, inspectWebp, stripPng, stripJpeg, stripWebp, containsAny };
  root.ImageMeta = api;
  if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof globalThis !== "undefined" ? globalThis : this);
