"""Cross-engine parity: js/av_meta.js must match upstream av_meta.py.

Two things are checked here. The buffer driver (inspectAv/cleanAv) has to agree
with upstream byte for byte, the same contract the image and text ports are held
to. The slice driver (inspectAvFile/cleanAvFile), which walks a File through
slice() so a video never has to be held in memory, then has to agree with the
buffer driver on the same fixtures: it is a second traversal over shared
primitives, and this is what stops it drifting away from the one parity checks.

One deliberate divergence is asserted rather than skipped, at the bottom.

Requires `node` and an upstream checkout (WATERMARKS_UPSTREAM_DIR, default
../watermarks-remover). Skips cleanly when either is missing.
"""
from __future__ import annotations

import base64
import json
import os
import shutil
import struct
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
UPSTREAM = Path(os.environ.get("WATERMARKS_UPSTREAM_DIR", ROOT.parent / "watermarks-remover"))
SCRIPTS = UPSTREAM / "service" / "scripts"
NODE = shutil.which("node")

pytestmark = pytest.mark.skipif(
    NODE is None or not (SCRIPTS / "av_meta.py").is_file(),
    reason="needs node and an upstream checkout (WATERMARKS_UPSTREAM_DIR)",
)

if (SCRIPTS / "av_meta.py").is_file():
    sys.path.insert(0, str(SCRIPTS))
    import av_meta  # type: ignore  # noqa: E402


# ---------------------------------------------------------------- builders

def iso_box(fourcc: bytes, payload: bytes) -> bytes:
    return struct.pack(">I", 8 + len(payload)) + fourcc + payload


XMP_UUID = bytes.fromhex("be7acfcb97a942e89c719994 91e3afac".replace(" ", ""))
XMP_AI = (b'<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF>'
          b"<digitalSourceType>trainedAlgorithmicMedia</digitalSourceType></rdf:RDF></x:xmpmeta>")
JUMBF = (b"\x00\x00\x00\x1fjumb\x00\x00\x00\x17jumdc2pa\x00\x11\x00\x10"
         b"\x80\x00\x00\xaa\x00\x38\x9b\x71\x03c2pa\x00")


def make_mp4(boxes: list[tuple[bytes, bytes]], *, brand: bytes = b"isomiso2avc1mp41",
             mdat: int = 512) -> bytes:
    out = iso_box(b"ftyp", brand[:4] + b"\x00\x00\x02\x00" + brand)
    for fourcc, payload in boxes:
        out += iso_box(fourcc, payload)
    return out + iso_box(b"mdat", bytes(mdat))


def moov(*sub: bytes) -> tuple[bytes, bytes]:
    return b"moov", iso_box(b"mvhd", bytes(100)) + b"".join(sub)


def udta(text: bytes) -> bytes:
    return iso_box(b"udta", b"\x00\x00\x00\x00tool" + text)


def syncsafe(n: int) -> bytes:
    return bytes([(n >> 21) & 0x7F, (n >> 14) & 0x7F, (n >> 7) & 0x7F, n & 0x7F])


def id3v2(frames: list[tuple[bytes, bytes]], *, major: int = 4, ext: bool = False,
          footer: bool = False, padding: int = 0) -> bytes:
    """A well-formed ID3v2.3/2.4 tag. v2.2 needs make_id3v22 instead."""
    body = b""
    if ext:
        # v2.4 counts the extended header's own size field; v2.3 does not.
        body += syncsafe(6) + b"\x01\x00" if major == 4 else struct.pack(">I", 6) + bytes(6)
    for frame_id, payload in frames:
        size = syncsafe(len(payload)) if major == 4 else struct.pack(">I", len(payload))
        body += frame_id + size + b"\x00\x00" + payload
    body += bytes(padding)
    flags = (0x40 if ext else 0) | (0x10 if footer and major == 4 else 0)
    header = b"ID3" + bytes([major, 0, flags]) + syncsafe(len(body))
    tag = header + body
    if footer and major == 4:
        tag += b"3DI" + header[3:10]
    return tag


def make_id3v22(payload: bytes) -> bytes:
    """A v2.2 tag: detected, never decomposed into frames."""
    body = b"TT2" + bytes([0, 0, len(payload)]) + payload
    return b"ID3" + bytes([2, 0, 0]) + syncsafe(len(body)) + body


MPEG_FRAME = b"\xff\xfb\x90\x00" + bytes(100)
FLAC_STREAM = b"fLaC" + b"\x80\x00\x00\x22" + bytes(34)


def geob(mime: bytes, *, encoding: int = 0, filename: bytes = b"c2pa",
         description: bytes = b"manifest", data: bytes = b"\x01\x02\x03") -> bytes:
    return bytes([encoding]) + mime + b"\x00" + filename + b"\x00" + description + b"\x00" + data


def riff_chunk(cid: bytes, payload: bytes) -> bytes:
    return cid + struct.pack("<I", len(payload)) + payload + (b"\x00" if len(payload) & 1 else b"")


def make_wav(chunks: list[tuple[bytes, bytes]]) -> bytes:
    body = riff_chunk(b"fmt ", struct.pack("<HHIIHH", 1, 1, 8000, 8000, 1, 8))
    for cid, payload in chunks:
        body += riff_chunk(cid, payload)
    body += riff_chunk(b"data", bytes(64))
    return b"RIFF" + struct.pack("<I", 4 + len(body)) + b"WAVE" + body


AI_TEXT = b"\x00Generated by OpenAI Sora"
BENIGN_TEXT = b"\x00Recorded on a phone in Taipei"

SAMPLES: dict[str, bytes] = {
    # ---- MP4 / MOV
    "mp4_clean": make_mp4([moov()]),
    "mp4_udta_ai": make_mp4([moov(udta(b"Generated by OpenAI Sora"))]),
    "mp4_udta_benign": make_mp4([moov(udta(b"Recorded on a phone in Taipei"))]),
    "mp4_xmp": make_mp4([moov(), (b"uuid", XMP_UUID + XMP_AI)]),
    "mp4_c2pa": make_mp4([moov(), (b"jumb", JUMBF)]),
    "mp4_uuid_plain": make_mp4([moov(), (b"uuid", b"\x11" * 16 + b"harmless camera note")]),
    "mp4_meta": make_mp4([moov(), (b"meta", b"\x00\x00\x00\x00" + iso_box(b"iinf", b"Generated by OpenAI"))]),
    "mp4_udta_and_xmp": make_mp4([moov(udta(b"Generated by OpenAI Sora")), (b"uuid", XMP_UUID + XMP_AI)]),
    "mov_quicktime": make_mp4([moov(udta(b"Generated by OpenAI Sora"))], brand=b"qt  qt  "),
    "m4a_audio": make_mp4([moov(udta(b"SynthID"))], brand=b"M4A M4A mp42"),
    # ---- WAV
    "wav_clean": make_wav([]),
    "wav_c2pa": make_wav([(b"C2PA", JUMBF)]),
    "wav_info_ai": make_wav([(b"LIST", b"INFO" + riff_chunk(b"ISFT", b"Generated by OpenAI\x00"))]),
    "wav_info_benign": make_wav([(b"LIST", b"INFO" + riff_chunk(b"ISFT", b"Audacity 3.4\x00"))]),
    "wav_list_not_info": make_wav([(b"LIST", b"adtl" + riff_chunk(b"note", b"Generated by OpenAI\x00"))]),
    "wav_id3_ai": make_wav([(b"id3 ", id3v2([(b"TSSE", AI_TEXT)]))]),
    "wav_id3_benign": make_wav([(b"id3 ", id3v2([(b"TSSE", BENIGN_TEXT)]))]),
    "wav_odd_chunk": make_wav([(b"LIST", b"INFO" + riff_chunk(b"ISFT", b"Generated by OpenAI\x00")),
                              (b"note", b"odd")]),
    # A chunk whose declared size overruns: the remainder is copied verbatim.
    "wav_overrun": make_wav([]) + b"junk" + struct.pack("<I", 0xFFFF) + b"tail",
    # ---- MP3
    "mp3_no_tag": MPEG_FRAME * 3,
    "mp3_clean_v24": id3v2([(b"TIT2", b"\x00A song")]) + MPEG_FRAME,
    "mp3_ai_v24": id3v2([(b"TIT2", b"\x00A song"), (b"TSSE", AI_TEXT)]) + MPEG_FRAME,
    "mp3_ai_v23": id3v2([(b"TIT2", b"\x00A song"), (b"TSSE", AI_TEXT)], major=3) + MPEG_FRAME,
    "mp3_ai_ext_v24": id3v2([(b"TSSE", AI_TEXT)], ext=True) + MPEG_FRAME,
    "mp3_ai_ext_v23": id3v2([(b"TSSE", AI_TEXT)], major=3, ext=True) + MPEG_FRAME,
    "mp3_ai_footer_v24": id3v2([(b"TSSE", AI_TEXT)], footer=True) + MPEG_FRAME,
    "mp3_padding": id3v2([(b"TSSE", AI_TEXT)], padding=32) + MPEG_FRAME,
    "mp3_v22_ai": make_id3v22(b"\x00Generated by OpenAI") + MPEG_FRAME,
    "mp3_v22_benign": make_id3v22(b"\x00A song") + MPEG_FRAME,
    "mp3_geob_c2pa": id3v2([(b"GEOB", geob(b"application/c2pa"))]) + MPEG_FRAME,
    # ---- FLAC
    "flac_plain": FLAC_STREAM,
    "flac_geob_c2pa": id3v2([(b"GEOB", geob(b"application/c2pa"))]) + FLAC_STREAM,
    "flac_geob_other": id3v2([(b"GEOB", geob(b"image/jpeg"))]) + FLAC_STREAM,
    "flac_geob_and_text": id3v2([(b"TIT2", b"\x00A song"), (b"GEOB", geob(b"application/c2pa"))]) + FLAC_STREAM,
    "flac_geob_utf16": id3v2([(b"GEOB", geob(b"application/c2pa", encoding=1,
                                             filename=b"c\x00\x00\x00", description=b"m\x00\x00\x00"))]) + FLAC_STREAM,
    "flac_geob_only_ext": id3v2([(b"GEOB", geob(b"application/c2pa"))], ext=True) + FLAC_STREAM,
    # ---- not audio or video at all
    "not_av": b"\x89PNG\r\n\x1a\n" + bytes(64),
}


def _js(mode: str, data: bytes, options: dict | None = None) -> dict:
    req = {"mode": mode, "file": base64.b64encode(data).decode(), "options": options or {}}
    proc = subprocess.run([NODE, str(ROOT / "tests" / "av_meta_cli.js")], input=json.dumps(req),
                          capture_output=True, text=True, check=True)
    return json.loads(proc.stdout)


def _py_inspect(data: bytes, fmt: str) -> tuple[bool, bool, list[str]]:
    if fmt == "mp4":
        return av_meta._inspect_mp4(data)
    if fmt == "wav":
        return av_meta._inspect_wav(data)
    if fmt == "mp3":
        return av_meta._inspect_id3v2(data)
    if fmt == "flac":
        return av_meta._inspect_flac(data)
    return False, False, ["unsupported format (MP4/MOV/M4A/WAV/MP3/FLAC)"]


def _py_clean(data: bytes, fmt: str, strip_all: bool) -> tuple[bytes, list[str]]:
    if fmt == "mp4":
        return av_meta._strip_mp4(data, strip_all_metadata=strip_all)
    if fmt == "wav":
        return av_meta._strip_wav(data, strip_all_metadata=strip_all)
    if fmt == "mp3":
        return av_meta._strip_id3v2(data, strip_all_metadata=strip_all)
    return av_meta._strip_flac(data, strip_all_metadata=strip_all)


@pytest.mark.parametrize("name", sorted(SAMPLES))
def test_detect_parity(name: str) -> None:
    data = SAMPLES[name]
    assert _js("detect", data)["format"] == av_meta.detect_av_format(data), name


@pytest.mark.parametrize("name", sorted(SAMPLES))
def test_inspect_parity(name: str) -> None:
    data = SAMPLES[name]
    fmt = av_meta.detect_av_format(data)
    has_c2pa, has_ai, findings = _py_inspect(data, fmt)
    js = _js("inspect", data)
    assert js["format"] == fmt, name
    assert (js["has_c2pa"], js["has_ai_metadata"], js["findings"]) == (has_c2pa, has_ai, findings), name


@pytest.mark.parametrize("name", sorted(k for k in SAMPLES if k != "not_av"))
@pytest.mark.parametrize("strip_all", [True, False])
def test_clean_parity(name: str, strip_all: bool) -> None:
    data = SAMPLES[name]
    fmt = av_meta.detect_av_format(data)
    py_bytes, py_actions = _py_clean(data, fmt, strip_all)
    js = _js("clean", data, {"stripAllMetadata": strip_all})
    assert "error" not in js, js
    assert js["format"] == fmt, name
    assert js["actions"] == py_actions, name
    assert base64.b64decode(js["data"]) == py_bytes, name


def test_clean_rejects_a_format_it_does_not_handle() -> None:
    js = _js("clean", SAMPLES["not_av"])
    assert "unsupported audio/video format" in js["error"]


def test_inspect_notes_only_when_the_format_is_unknown() -> None:
    assert _js("inspect", SAMPLES["not_av"])["notes"] == [
        "format not fully inspected; only MP4/MOV/M4A/WAV/MP3/FLAC are supported"]
    assert _js("inspect", SAMPLES["mp4_clean"])["notes"] == []


# ------------------------------------------------- the two drivers must agree

@pytest.mark.parametrize("name", sorted(SAMPLES))
def test_slice_driver_inspect_matches_buffer_driver(name: str) -> None:
    data = SAMPLES[name]
    assert _js("inspect-file", data) == _js("inspect", data), name
    assert _js("detect-file", data) == _js("detect", data), name


@pytest.mark.parametrize("name", sorted(k for k in SAMPLES if k != "not_av"))
@pytest.mark.parametrize("strip_all", [True, False])
def test_slice_driver_clean_matches_buffer_driver(name: str, strip_all: bool) -> None:
    data = SAMPLES[name]
    opts = {"stripAllMetadata": strip_all}
    assert _js("clean-file", data, opts) == _js("clean", data, opts), name


# ------------------------------------------------------------- the divergence

TRUNCATED_MP4 = SAMPLES["mp4_udta_ai"][:-256]


def test_truncated_mp4_keeps_its_tail_where_upstream_drops_it() -> None:
    """guillaumemeyer/watermarks-remover#240.

    upstream's _strip_moov_udta rebuilds the file from the boxes that parsed, so
    everything after the first box whose size overruns the data is discarded,
    even though the strip_isobmff pass just before it preserved that tail and
    put "kept N bytes of truncated tail" in the action list. This port keeps the
    tail, as upstream #182 already established for PNG and ISOBMFF.
    """
    upstream_bytes, upstream_actions = av_meta._strip_mp4(TRUNCATED_MP4, strip_all_metadata=True)
    assert any("kept" in a and "truncated tail" in a for a in upstream_actions)
    assert len(upstream_bytes) < len(TRUNCATED_MP4) // 2, "upstream is expected to lose the media here"

    for mode in ("clean", "clean-file"):
        js = _js(mode, TRUNCATED_MP4, {"stripAllMetadata": True})
        cleaned = base64.b64decode(js["data"])
        assert js["actions"] == upstream_actions, mode
        assert len(cleaned) == len(TRUNCATED_MP4), mode
        # Only the metadata was rewritten; the truncated tail is byte-identical.
        tail = len(TRUNCATED_MP4) - len(upstream_bytes)
        assert cleaned[-tail:] == TRUNCATED_MP4[-tail:], mode


def test_truncated_mp4_still_inspects_like_upstream() -> None:
    has_c2pa, has_ai, findings = av_meta._inspect_mp4(TRUNCATED_MP4)
    for mode in ("inspect", "inspect-file"):
        js = _js(mode, TRUNCATED_MP4)
        assert (js["has_c2pa"], js["has_ai_metadata"], js["findings"]) == (has_c2pa, has_ai, findings), mode
