"""Cross-engine parity for common.classify_finding_confidence.

js/stylometry.js mirrors this one helper out of upstream's common.py, because
`StylometryReport.to_dict()` calls it and the Inspector shows what it returns.
Nothing else in this project mirrors common.py, so the drift check tracks only
this definition's slice of the file (see scripts/upstream-sources.json).

The stylometry fixtures reach the helper only through findings this scorer
happens to produce, all of which start with "AI ". Every other bucket, and the
ordering between them, is exercised here instead: the same string can match
several bucket lists, so the order the checks run in is the behaviour.

Upstream #273 added the first rule, which is the case a whole-file hash would
have caught and did not: a Layer A space homoglyph is informational, while
every other Layer A finding stays probable.

Requires `node` and an upstream checkout (WATERMARKS_UPSTREAM_DIR, default
../watermarks-remover). Skips cleanly when either is missing.
"""
from __future__ import annotations

import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
UPSTREAM = Path(os.environ.get("WATERMARKS_UPSTREAM_DIR", ROOT.parent / "watermarks-remover"))
SCRIPTS = UPSTREAM / "service" / "scripts"
NODE = shutil.which("node")

pytestmark = pytest.mark.skipif(
    NODE is None or not (SCRIPTS / "common.py").is_file(),
    reason="needs node and an upstream checkout (WATERMARKS_UPSTREAM_DIR)",
)

if (SCRIPTS / "common.py").is_file():
    sys.path.insert(0, str(SCRIPTS))
    import common  # type: ignore  # noqa: E402

FINDINGS = [
    # Upstream #273: space homoglyphs are weaker context than invisible carriers.
    "Layer-A: U+00A0 NO-BREAK SPACE (space)",
    "layer-a: U+2009 THIN SPACE (space)",
    "Layer-A: U+200B ZERO WIDTH SPACE (carrier)",
    "Layer-A: U+FE00 variation selector",
    # The rule is anchored at both ends, so neither half alone should fire it.
    "note about layer-a spacing (space)",
    "Layer-A: something else entirely (space) and more",
    # confirmed
    "c2patool reports a valid manifest",
    "PNG chunk caBX (c2pa-related manifest)",
    "PNG chunk jumb",
    "JPEG APP11 segment",
    "XMP digitalSourceType=trainedAlgorithmicMedia",
    "compositeWithTrainedAlgorithmicMedia",
    "softwareAgent: some tool",
    # informational
    "info: nothing conclusive",
    "CMS generator tag",
    "XMP packet present",
    "unsupported container",
    "not fully inspected",
    "format not recognized",
    "SVG <metadata> present",
    "not a valid AVIF (no ISOBMFF boxes found)",
    "truncated chunk",
    "bad segment length",
    # likely_false_positive
    "byte-scan C2PA markers: c2pa, C2PA",
    "byte-scan C2PA BMFF content-provenance user type",
    # probable
    "AI: generator marker",
    "marker: Generated by OpenAI",
    "meta: something",
    "frontmatter key",
    "JSON-LD block",
    "attr: data-ai",
    "PNG tEXt Software=ChatGPT",
    "JPEG APP1 EXIF",
    "EXIF Software tag",
    "PDF-structured metadata",
    # default bucket
    "AI phrase marker 'delve into' found (2x)",
    "AI cadence phrase 'in conclusion' (1x)",
    "something with no bucket at all",
    "",
    # Ordering: a string in more than one list resolves by the order of the
    # checks, not by which list is longer.
    "byte-scan hit inside a PNG chunk jumb",
    "info: PNG tEXt Software=ChatGPT",
    "layer-a byte-scan (space)",
]


def _js(findings: list[str]) -> list[str]:
    req = {"mode": "confidence", "findings": findings}
    proc = subprocess.run([NODE, str(ROOT / "tests" / "stylometry_cli.js")], input=json.dumps(req),
                          capture_output=True, text=True, check=True)
    return json.loads(proc.stdout)["levels"]


def test_finding_confidence_parity() -> None:
    js = _js(FINDINGS)
    py = [common.classify_finding_confidence(f) for f in FINDINGS]
    assert js == py, [(f, a, b) for f, a, b in zip(FINDINGS, js, py) if a != b]


def test_the_new_space_rule_actually_moves_something() -> None:
    """Guard against the fixtures agreeing for the wrong reason.

    Both engines returning "probable" for every Layer A finding would pass the
    parity test above while missing #273 entirely.
    """
    assert common.classify_finding_confidence("Layer-A: U+00A0 NO-BREAK SPACE (space)") == "informational"
    assert common.classify_finding_confidence("Layer-A: U+200B ZERO WIDTH SPACE (carrier)") == "probable"
    assert _js(["Layer-A: U+00A0 NO-BREAK SPACE (space)"]) == ["informational"]
    assert _js(["Layer-A: U+200B ZERO WIDTH SPACE (carrier)"]) == ["probable"]
